ci: fix issues related to `prettier-check` in CI (#501)
Summary:
Currently our CI is failing due to various issues related to the `verify-addons-folder.py` script.

This commit fixes a linter issue related to `prettier-check` that made the aforementioned script fail.

Pull Request resolved: https://github.com/facebook/sapling/pull/501

Test Plan:
## Before

Ran `./verify-addons-folder.py`, and failed with

```
RuntimeError: command failed: yarn run prettier-check
```

Also ran `yarn run prettier-check`, and failed with:
```
yarn run v1.22.19
$ prettier --check .
Checking formatting...
[warn] isl/src/analytics/index.ts
[warn] Code style issues found in the above file. Forgot to run Prettier?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
```

## After

Ran `./verify-addons-folder.py`, and now failed with `RuntimeError: command failed: yarn codegen` instead.

Also, `yarn run prettier-check` worked without issues.

Reviewed By: muirdm

Differential Revision: D42818837

Pulled By: sggutier

fbshipit-source-id: 5478356ad20766c5af7634da19763410236b3059