github: install gh cli in the dockerfile
install the github cli as sapling and review stack need it

Currently the verify-addons-folder.py CI is failing due to missing gh cli with:

```
spawn gh ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at /__w/sapling/sapling/addons/isl-server/src/github/queryGraphQL.ts:50:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5))
    at new NodeError (node:internal/errors:387:5)
    at TypedEventEmitter.emit (node:events:502:17)
    at GitHubCodeReviewProvider.<anonymous> (/__w/sapling/sapling/addons/isl-server/src/github/githubCodeReviewProvider.ts:74:36)
    at Generator.throw (<anonymous>)
    at rejected (/__w/sapling/sapling/addons/isl-server/src/github/githubCodeReviewProvider.ts:12:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_UNHANDLED_ERROR',
  context: Error: GhNotInstalledError: Error: Command failed with ENOENT: gh api graphql -f searchQuery=repo:facebook/sapling is:pr author:@me -F numToFetch=100 --hostname github.com -f query=
```

Once the docker images are rebuilt we should start to see something different!

Test Plan:

Before, gh cli missing from the image
```
docker build -t sapling-cli-ubuntu-22.04 -f sapling-cli-ubuntu-22.04.Dockerfile .
docker run -ti sapling-cli-ubuntu-22.04 gh --help
Error: crun: executable file `gh` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found

```

After, image contains gh cli
```
docker build -t sapling-cli-ubuntu-22.04 -f sapling-cli-ubuntu-22.04.Dockerfile .
docker run -ti sapling-cli-ubuntu-22.04 gh --help
...
LEARN MORE
  Use 'gh <command> <subcommand> --help' for more information about a command.
  Read the manual at https://cli.github.com/manual

```

Repeated above with the 20.04 image, same results