Fix missing backtrace method on stable toolchain
Summary:
Fixes `oss-mononoke-linux-getdeps` failure:

   error[E0599]: no method named `backtrace` found for struct `Arc<anyhow::Error>` in the current scope
     --> megarepo_api/megarepo_error/src/lib.rs:36:24
      |
   36 |                 self.0.backtrace()
      |                        ^^^^^^^^^ method not found in `Arc<anyhow::Error>`
   ...
   64 | cloneable_error!(InternalError);
      | ------------------------------- in this macro invocation
      |
      = note: this error originates in the macro `cloneable_error` (in Nightly builds, run with -Z macro-backtrace for more info)

   error[E0599]: no method named `backtrace` found for struct `Arc<anyhow::Error>` in the current scope
     --> megarepo_api/megarepo_error/src/lib.rs:58:56
      |
   58 |                 demand.provide_ref::<Backtrace>(self.0.backtrace());
      |                                                        ^^^^^^^^^ method not found in `Arc<anyhow::Error>`
   ...
   64 | cloneable_error!(InternalError);
      | ------------------------------- in this macro invocation
      |
      = note: this error originates in the macro `cloneable_error` (in Nightly builds, run with -Z macro-backtrace for more info)

   error[E0599]: no method named `backtrace` found for struct `Arc<anyhow::Error>` in the current scope
     --> megarepo_api/megarepo_error/src/lib.rs:36:24
      |
   36 |                 self.0.backtrace()
      |                        ^^^^^^^^^ method not found in `Arc<anyhow::Error>`
   ...
   65 | cloneable_error!(RequestError);
      | ------------------------------ in this macro invocation
      |
      = note: this error originates in the macro `cloneable_error` (in Nightly builds, run with -Z macro-backtrace for more info)

   error[E0599]: no method named `backtrace` found for struct `Arc<anyhow::Error>` in the current scope
     --> megarepo_api/megarepo_error/src/lib.rs:58:56
      |
   58 |                 demand.provide_ref::<Backtrace>(self.0.backtrace());
      |                                                        ^^^^^^^^^ method not found in `Arc<anyhow::Error>`
   ...
   65 | cloneable_error!(RequestError);
      | ------------------------------ in this macro invocation
      |
      = note: this error originates in the macro `cloneable_error` (in Nightly builds, run with -Z macro-backtrace for more info)

   For more information about this error, try `rustc --explain E0599`.
   error: could not compile `megarepo_error` due to 4 previous errors
   warning: build failed, waiting for other jobs to finish...

Reviewed By: dtolnay

Differential Revision: D40045398

fbshipit-source-id: a801c9ab4f1d1e550b1a8d90bd5413c5421f9bdb