copytrace: remove undefined symbol `dbm._Databse`
Summary:
Pyre automation added `dbm._Databse` in D42385084 (https://github.com/facebook/sapling/commit/c95dcdc6644ba6b9b1aa9972e6b2fbaf1761dfca). But `dbm._Databse` does not
exist and cause

  $ hg bookmark book1
  Traceback (most recent call last):
    File "eden/scm/edenscm/__init__.py", line 86, in run
      dispatch.runchgserver(args[2:])
    File "eden/scm/edenscm/dispatch.py", line 368, in runchgserver
      _preimportmodules()
    File "eden/scm/edenscm/dispatch.py", line 348, in _preimportmodules
      extensions.preimport(extname)
    File "eden/scm/edenscm/extensions.py", line 208, in preimport
      mod = getattr(__import__("edenscm.ext.%s" % name).ext, name)
    File "eden/scm/edenscm/ext/copytrace.py", line 169, in <module>
      ) -> Tuple[Optional[dbm._Database], Optional[Tuple[Type[dbm._error], Type[OSError]]]]:
  AttributeError: module 'dbm' has no attribute '_Database'

Reviewed By: zzl0

Differential Revision: D42456269

fbshipit-source-id: f6494f66b0676b5f2525110bc04060db9d85c027