render mismatched commits as underlying RootIDs
Summary:
# Context

The Eden thrift error on commit/parent mismatch should look like this:

```
error.EdenError: error computing status: requested parent commit is out-of-date: requested 681e0c9978e24003b6432cf86f8a5e9b51d0f4af, but current parent commit is 49aacbce01b5b7729b5a7ad6d551d7202d8b8c04.
```

On FilteredFS repos, it looks like this (notice the extra `(` and `null` at the beginning and end):

```
error.EdenError: error computing status: requested parent commit is out-of-date: requested (681e0c9978e24003b6432cf86f8a5e9b51d0f4afnull, but current parent commit is (49aacbce01b5b7729b5a7ad6d551d7202d8b8c04null.
```

The extra parts are added because we naively print out FilteredRootIDs as hex (see https://www.internalfb.com/code/fbsource/[8a227dc30524]/fbcode/eden/fs/inodes/EdenMount.cpp?lines=1781-1787). FilteredRootIDs have extra bits on either side (the length at the beginning and the filter at the end), so those parts of included in the error message.

# A potential solution:

For FilteredFS repos, I want to render only the underlying RootID (so the `(` and `null` don’t get printed). We have renderRootId() that kind of does this, but it renders the underlying RootID as binary. See:

```
error.EdenError: error computing status: requested parent commit is out-of-date: requested h�x�@�C,�o�^�Q���, but current parent commit is I�����r�Zz��Q� -��.
  Try running `eden doctor` to remediate
```

I want it to be rendered as hex. If I round trip the conversion by going from HexFilteredRootId -> BinaryUnderlyingRootId -> HexUnderlyingRootId, then everything works as expected on both FilteredFS and Vanilla EdenFS repos. The extra round trip is basically a no-op for Vanilla EdenFS repos.

# This diff

This diff implements the round-trip so that FilteredFS repos print out correctly formatted underlying ObjectIDs.

Reviewed By: jdelliot

Differential Revision: D56593397

fbshipit-source-id: eb41f5fad5dff0289ed4ddad4270b91a3aa3c3d4