Fix mononoke-git-server deps
Summary:
```lang=log,counterexample
Error evaluating build file: `fbcode//eden/mononoke/tests/integration/mononoke_git_server:BUCK`

Caused by:
    Traceback (most recent call last):
      * fbcode/eden/mononoke/tests/integration/mononoke_git_server/BUCK:20, in <module>
          dott_test(
      * fbcode/eden/mononoke/tests/integration/facebook/fb_manifest_deps.bzl:170, in dott_test
          _dott_test(name, dott_files, deps, use_mysql, False, rust_allow_oss_build = r...
      * fbcode/eden/mononoke/tests/integration/facebook/fb_manifest_deps.bzl:218, in _dott_test
          fail("Unknown target", d, "in dependencies for", name)
    error: fail: Unknown target //eden/mononoke/servers/multi_repo_land:multi_repo_land_service in dependencies for mononoke-git-server
       --> fbcode/eden/mononoke/tests/integration/facebook/fb_manifest_deps.bzl:218:13
        |
    218 |             fail("Unknown target", d, "in dependencies for", name)
        |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |
```

Reviewed By: RajivTS

Differential Revision: D94923100

fbshipit-source-id: aab877e523e9c0a24d2563232bedabf1a6b44222