remotefilelog: stop wrapping exchange.pull
Summary:
The `exchangepull` code path could trigger (legacy) "peer" creation that fails:

  File "static:sapling.ext.remotefilelog", line 786, in exchangepull
    if hasattr(remote, "_callstream"):
  File "static:sapling.connectionpool", line 62, in __getattr__
    self._real_connection = self._real_connection_pool.get(
  File "static:sapling.connectionpool", line 124, in get
    peer = hg.peer(self._repo.ui, {}, path)
    # path = 'mononoke://mononoke.internal.tfbnw.net/aosp'
  File "static:sapling.hg", line 180, in peer
    obj = _peerlookup(path).instance(rui, path, create, initial_config=None)
    # create = False
    # path = 'mononoke://mononoke.internal.tfbnw.net/aosp'
  File "static:sapling.mononokepeer", line 286, in __init__
    self._validaterepo()
  File "static:sapling.mononokepeer", line 461, in _validaterepo
    self._abort(
  File "static:sapling.stdiopeer", line 72, in _abort
    raise exception
  sapling.error.BadResponseError: unexpected server response: "404 Not Found":

It seems no longer necessary. So let's remove it.

Reviewed By: muirdm

Differential Revision: D76554673

fbshipit-source-id: 58b955d56de5788ee67cb5a6ce832abedf42b85c