distutils_rust: handle mt output with different locale setting
Summary:
`distutils_rust` tries to use `mt` to merge the "long path aware" Windows
manifest. It tries to deal with 2 cases:

- The exe already has an embedded manifest. Use `-inputresource` to merge them.
- The exe does not have an embedded manifest. Do not use `-inputresource` since
  it will cause an error.

It does so by first passing `-inputresource`, then drop it if the error message
contains "The specified resource type cannot be found in the image file".

However, the error message is translated. Depending on system locale setting,
`mt` might output:

  mt : general error c101008c: Failed to read the manifest from the resource of file "hg.exe". The specified resource type cannot be found in the image file.
  mt : general error c101008c: Failed to read the manifest from the resource of file "hg.exe". 指定的映像文件不包含资源区域。

So let's check the error code `c101008c` instead.

Reviewed By: andll

Differential Revision: D27885096

fbshipit-source-id: 3d42a3b88ae593434e7104c7899bf6b4f3366180