Back out "Fix UX hurdle when using `--local-configerator-path`"
Summary:
Original commit changeset: 2cd1aef25bf8

Original Phabricator Diff: D51549531

The original diff broke newadmin:

```
buck run @//mode/opt //eden/mononoke/tools/admin:newadmin -- --prod repo-info -R fbsource
```
```
Soft Error: source_file_missing: Source file `examples/WhoAmI.cpp` does not exist as a member of package `fbcode//manifold/client`.
Buck UI: https://www.internalfb.com/buck2/889fddfe-4fd0-4576-8db8-82d615441381
Network: Up: 5.2MiB  Down: 3.8GiB  (reSessionID-18bdef56-4c6e-4222-b576-6a267c90e7c5)
Jobs completed: 117272. Time elapsed: 3:30.3s.
Cache hits: 99%. Commands: 41980 (cached: 41979, remote: 0, local: 1)
BUILD SUCCEEDED
Error: entity not found by Configerator C++ client: scm/mononoke/tunables/default.materialized_JSON
```
And if only reverting that part of the diff,
```
buck run @//mode/opt //eden/mononoke/tools/admin:newadmin -- --prod repo-info -R fbsource
```
```
File changed: fbcode//eden/mononoke/cmdlib/mononoke_app/src/args/tunables.rs
Soft Error: source_file_missing: Source file `examples/WhoAmI.cpp` does not exist as a member of package `fbcode//manifold/client`.
Buck UI: https://www.internalfb.com/buck2/d09f3994-b004-4129-b812-065e469717a1
Network: Up: 744KiB  Down: 102MiB  (reSessionID-f0aa7a6c-aca0-4f37-8a4c-c73ec4df66fa)
Jobs completed: 115610. Time elapsed: 3:33.1s.
Cache hits: 0%. Commands: 5 (cached: 0, remote: 0, local: 5)
BUILD SUCCEEDED
Error: entity not found by Configerator C++ client: scm/mononoke/repos/tiers/prod.materialized_JSON
```
Backing out of it for now.

Reviewed By: YousefSalama

Differential Revision: D51561689

fbshipit-source-id: b72ffd622a2a73398c219e1b4faf850d3827dedb