telemetry: fix typing for NullTelemetrySample
Summary:
When writing D78565551, `add_bool().log()` unexpectedly failed many tests due to `AttributeError: 'NoneType' object has no attribute 'log'`, even though it passes pyre.

Traced it down to NullTelemetrySample. This diff replaces `pass` with `return self` to prevent the surprises.

Reviewed By: ViniGupta08

Differential Revision: D78579482

fbshipit-source-id: 91b782ad4a4ebda284e666d27e26746b2744cf45