packaging: fix manylinux build script
Summary:
Previously, `get_sl_python_version` fails because the `sl` cannot run without a
`lib/python3.12/lib-dynload` directory relative to the executable. It's a
chick-egg problem, since `get_sl_python_version` is to figure out the "3.12"
part of the lib-dynload path. Fix this by using the `python` binary to obtain
the "3.12" version string.

For context, the failure on GitHub CI looks like:

  Python path configuration:
    PYTHONHOME = (not set)
    PYTHONPATH = (not set)
    program name = '/__w/sapling/sapling/eden/scm/sl'
    isolated = 0
    environment = 1
    user site = 1
    safe_path = 0
    import site = 0
    is in build tree = 0
    stdlib dir = '/__w/sapling/sapling/eden/scm/lib/python3.12'
    sys._base_executable = '/__w/sapling/sapling/eden/scm/sl'
    sys.base_prefix = '/__w/sapling/sapling/eden/scm'
    sys.base_exec_prefix = '/opt/_internal/cpython-3.12.11'
    sys.platlibdir = 'lib'
    sys.executable = '/__w/sapling/sapling/eden/scm/sl'
    sys.prefix = '/__w/sapling/sapling/eden/scm'
    sys.exec_prefix = '/opt/_internal/cpython-3.12.11'
    sys.path = [
      '/__w/sapling/sapling/eden/scm/lib/python312.zip',
      '/__w/sapling/sapling/eden/scm/lib/python3.12',
      '/opt/_internal/cpython-3.12.11/lib/python3.12/lib-dynload',
    ]
  Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
  Python runtime state: core initialized
  Traceback (most recent call last):
    File "static:encodings", line 33, in <module>
  ImportError: attempted relative import with no known parent package
  Traceback (most recent call last):
    File "/__w/sapling/sapling/eden/scm/./packaging/manylinux/build.py", line 125, in <module>
      main()
    File "/__w/sapling/sapling/eden/scm/./packaging/manylinux/build.py", line 118, in main
      add_python_native_stdlib(sl_path, python_prefix, tar)
    File "/__w/sapling/sapling/eden/scm/./packaging/manylinux/build.py", line 63, in add_python_native_stdlib
      version = get_sl_python_version(sl_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/__w/sapling/sapling/eden/scm/./packaging/manylinux/build.py", line 50, in get_sl_python_version
      out = subprocess.check_output(
            ^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/python/cp312-cp312/lib/python3.12/subprocess.py", line 466, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/python/cp312-cp312/lib/python3.12/subprocess.py", line 571, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['/__w/sapling/sapling/eden/scm/sl', 'debugpython', '-c', "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')"]' returned non-zero exit status 1.

Reviewed By: muirdm

Differential Revision: D75994450

fbshipit-source-id: 90c3673bd208f377ba068cb7593f1a70dd978e6f