website: improve error message when a platform release is missing
Summary:
The current error is hard to understand:

  Error:  Error: Unable to build website for locale en.
      at tryToBuildLocale (/home/runner/work/sapling/sapling/website/node_modules/docusaurus/core/lib/commands/build/build.js:78:15)
      at async /home/runner/work/sapling/sapling/website/node_modules/docusaurus/core/lib/commands/build/build.js:34:9
      ... 4 lines matching cause stack trace ...
      at async file:///home/runner/work/sapling/sapling/website/node_modules/docusaurus/core/bin/docusaurus.mjs:44:3 {
    [cause]: Error: Docusaurus static site generation failed for 1 paths:
    - "/docs/introduction/installation"
        at generateStaticFiles (/home/runner/work/sapling/sapling/website/node_modules/docusaurus/core/lib/ssg/ssg.js:129:15)
        at async executeSSG (/home/runner/work/sapling/sapling/website/node_modules/docusaurus/core/lib/ssg/ssgExecutor.js:29:23)
        ... 9 lines matching cause stack trace ...
        at async file:///home/runner/work/sapling/sapling/website/node_modules/docusaurus/core/bin/docusaurus.mjs:44:3 {
      [cause]: AggregateError
          at generateStaticFiles (/home/runner/work/sapling/sapling/website/node_modules/docusaurus/core/lib/ssg/ssg.js:130:20)
          at async executeSSG (/home/runner/work/sapling/sapling/website/node_modules/docusaurus/core/lib/ssg/ssgExecutor.js:29:23)
          at async buildLocale (/home/runner/work/sapling/sapling/website/node_modules/docusaurus/core/lib/commands/build/buildLocale.js:60:31)
          at async runBuildLocaleTask (/home/runner/work/sapling/sapling/website/node_modules/docusaurus/core/lib/commands/build/build.js:93:5)
          at async /home/runner/work/sapling/sapling/website/node_modules/docusaurus/core/lib/commands/build/build.js:74:13
          at async tryToBuildLocale (/home/runner/work/sapling/sapling/website/node_modules/docusaurus/core/lib/commands/build/build.js:70:9)
          at async /home/runner/work/sapling/sapling/website/node_modules/docusaurus/core/lib/commands/build/build.js:34:9
          at async mapAsyncSequential (/home/runner/work/sapling/sapling/website/node_modules/docusaurus/utils/lib/jsUtils.js:21:24)
          at async Command.build (/home/runner/work/sapling/sapling/website/node_modules/docusaurus/core/lib/commands/build/build.js:33:5)
          at async Promise.all (index 0)
          at async runCLI (/home/runner/work/sapling/sapling/website/node_modules/docusaurus/core/lib/commands/cli.js:56:5)
          at async file:///home/runner/work/sapling/sapling/website/node_modules/docusaurus/core/bin/docusaurus.mjs:44:3 {
        [errors]: [
          Error: Can't render static file for pathname "/docs/introduction/installation"
              at generateStaticFile (/home/runner/work/sapling/sapling/website/node_modules/docusaurus/core/lib/ssg/ssg.js:167:15)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
              at runNextTicks (node:internal/process/task_queues:64:3)
              at process.processImmediate (node:internal/timers:447:9)
              at async /home/runner/work/sapling/sapling/website/node_modules/p-map/index.js:57:22 {
            [cause]: TypeError: Cannot read properties of null (reading 'name')
                at _createMdxContent (/home/runner/work/sapling/sapling/website/build/__server/assets/js/ac68e5b7.0562bb15.js:384:44)
                at MDXContent (/home/runner/work/sapling/sapling/website/build/__server/assets/js/ac68e5b7.0562bb15.js:503:8)
                at Uc (server.bundle.js:10914:44)
                at Xc (server.bundle.js:10916:253)
                at Z (server.bundle.js:10922:89)
                at Xc (server.bundle.js:10920:231)
                at Z (server.bundle.js:10922:89)
                at Xc (server.bundle.js:10916:481)
                at Z (server.bundle.js:10922:89)
                at Xc (server.bundle.js:10916:481)
                at Z (server.bundle.js:10922:89)
                at Yc (server.bundle.js:10925:98)
                at $c (server.bundle.js:10924:140)
                at Z (server.bundle.js:10922:345)
                at Xc (server.bundle.js:10917:476)
                at Z (server.bundle.js:10922:89)
                at Xc (server.bundle.js:10916:481)
                at Z (server.bundle.js:10922:89)
                at Yc (server.bundle.js:10925:98)
                at $c (server.bundle.js:10924:140)
                at Z (server.bundle.js:10922:345)
                at Yc (server.bundle.js:10925:98)
                at Xc (server.bundle.js:10917:145)
                at Z (server.bundle.js:10922:89)
                at Xc (server.bundle.js:10916:481)
                at Z (server.bundle.js:10922:89)
                at Yc (server.bundle.js:10925:98)
                at $c (server.bundle.js:10924:140)
                at Z (server.bundle.js:10922:345)
                at Yc (server.bundle.js:10925:98)
                at Xc (server.bundle.js:10917:145)
                at Z (server.bundle.js:10922:89)
                at Yc (server.bundle.js:10925:98)
                at $c (server.bundle.js:10924:140)
                at Z (server.bundle.js:10922:345)
                at Yc (server.bundle.js:10925:98)
                at Xc (server.bundle.js:10917:145)
                at Z (server.bundle.js:10922:89)
                at Yc (server.bundle.js:10925:98)
                at $c (server.bundle.js:10924:140)
                at Z (server.bundle.js:10922:345)
                at Yc (server.bundle.js:10925:98)
                at Xc (server.bundle.js:10917:145)
                at Z (server.bundle.js:10922:89)
                at Yc (server.bundle.js:10925:98)
                at $c (server.bundle.js:10924:140)
                at Z (server.bundle.js:10922:345)
                at Yc (server.bundle.js:10925:98)
                at Xc (server.bundle.js:10917:145)
                at Z (server.bundle.js:10922:89)
          }
        ]
      }
    }
  }

Reviewed By: muirdm

Differential Revision: D75240253

fbshipit-source-id: a51ccc8e7e3f0922db9c8b0dd93f6dbffa616d5d