getdeps: fix inheritance on ImportPriority formatter
Summary:
getdeps fails with the following error:

```
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-FHukGLl-vQ54P4P_dMfig6Np0_gq5419Adqk0Dqpexo/include/fmt/format.h: In instantiation of ‘constexpr fmt::v11::enable_if_t<((fmt::v11::detail::type_constant<decltype (fmt::v11::detail::arg_mapper<Context>().map(declval<const T&>())), typename Context::char_type>::value == fmt::v11::detail::type::custom_type) && (! std::is_fundamental<T>::value)), OutputIt> fmt::v11::detail::write(OutputIt, const T&) [with Char = char; OutputIt = fmt::v11::basic_appender<char>; T = facebook::eden::ImportPriority; Context = fmt::v11::context; fmt::v11::enable_if_t<((fmt::v11::detail::type_constant<decltype (fmt::v11::detail::arg_mapper<Context>().map(declval<const T&>())), typename Context::char_type>::value == fmt::v11::detail::type::custom_type) && (! std::is_fundamental<T>::value)), OutputIt> = fmt::v11::basic_appender<char>; typename Context::char_type = char; decltype (fmt::v11::detail::arg_mapper<Context>().map(declval<const T&>())) = const facebook::eden::ImportPriority&]’:
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-FHukGLl-vQ54P4P_dMfig6Np0_gq5419Adqk0Dqpexo/include/fmt/format.h:4187:3:   required from ‘std::string fmt::v11::to_string(const T&) [with T = facebook::eden::ImportPriority; typename std::enable_if<((! std::is_integral<_Tp>::value) && (! fmt::v11::detail::has_format_as<T>::value)), int>::type <anonymous> = 0; std::string = std::__cxx11::basic_string<char>]’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/eden/eden/fs/store/test/ImportPriorityTest.cpp:39:3:   required from here
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-FHukGLl-vQ54P4P_dMfig6Np0_gq5419Adqk0Dqpexo/include/fmt/format.h:3711:13: error: ‘struct fmt::v11::formatter<facebook::eden::ImportPriority>’ has no member named ‘parse’
```

This diff adds the inheritance to the formatter to address this

Reviewed By: kavehahmadi60

Differential Revision: D62416110

fbshipit-source-id: 8261e7f5eaf75c466cb1eff4b60a25628b0bdde1