Fix test-lfs-test-server.t
Summary:
test-lfs-test-server.t is failing because of spurious output from Bash:

```
======================================================================
FAIL: test_lfs_test_server_t (scm.hg.tests.unittestify.hgtests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/strager/fbsource/fbcode/buck-out/dev/gen/scm/hg/tests/hg_run_tests#binary,link-tree/scm/hg/tests/unittestify.py", line 96, in runsingletest
    raise self.failureException(err + out)
AssertionError:
 --- test-lfs-test-server.t
+++ test-lfs-test-server.t.err
@@ -158,6 +158,7 @@
 (Restart the server in a different location so it no longer has the content)

   $ $PYTHON $RUNTESTDIR/killdaemons.py $DAEMON_PIDS
+  $TESTTMP.sh: line 116: 2128544 Terminated              lfs-test-server &>lfs-server.log
   $ rm $DAEMON_PIDS
   $ mkdir $TESTTMP/lfs-server2
   $ cd $TESTTMP/lfs-server2
@@ -187,3 +188,4 @@
 Clean up:

   $ $PYTHON $RUNTESTDIR/killdaemons.py $DAEMON_PIDS
+  $TESTTMP.sh: line 140: 2130121 Terminated              lfs-test-server &>lfs-server.log  (wd: ~/lfs-server2)

ERROR: test-lfs-test-server.t output changed
!
Failed test-lfs-test-server.t: output changed
```

If this this test wasn't broken, it would have caught a bug introduced by D9478744 (fixed by D9619464). Fix the failures to make the test pass again.

Reviewed By: quark-zju

Differential Revision: D9619647

fbshipit-source-id: 989db431a28ab2d491ced70dc9113998b0ddb5f5