clidispatch: require repo/wdir feature
Summary:
Resolves the `cargo check` issue:

  error[E0599]: no method named `working_copy` found for mutable reference `&mut repo::Repo` in the current scope
     --> lib/clidispatch/src/dispatch.rs:425:39
      |
  425 |                     let mut wc = repo.working_copy()?;
      |                                       ^^^^^^^^^^^^ method not found in `&mut Repo`

Reviewed By: sggutier

Differential Revision: D56592489

fbshipit-source-id: dba9077630bd56f2711a3ed30580f3901a1d4c79