targets: add rust_library and rust_binary shims
Summary:
By default, `rust_library` and `rust_binary` inherits the monorepo's
`Cargo.toml` for 3p deps. This means, if a cargo feature `x` of crate `y` is
used by anything in the monorepo, we inherits the cargo feature even if `sl`
itself does not need the feature. This becomes even more problematic if the
feature `x` relies on nightly rustc. The monorepo rustc allows nightly
features, but `sl` codebase should be buildable using stable rustc.

Example failure:

  error[E0554]: `#![feature]` may not be used on the stable release channel
  --> fbsource/third-party/rust/vendor/smallvec-1.15.2/src/lib.rs:95:41
     |
  95 | #![cfg_attr(feature = "specialization", feature(specialization))]
     |                                         ^^^^^^^^^^^^^^^^^^^^^^^

This diff introduces a shim to rust_library and rust_binary so we can later use
it to auto-rewrite the autocargo overrides.

Reviewed By: genevievehelsel

Differential Revision: D111799588

fbshipit-source-id: 930849b7f16e2a9f3bc5a25f27fa2c7da4321f83