gitimport: Stop swallowing errors in finalize_batch
Summary:
Currently, if the finalize_batch steps fail, all we get for diagnostics is:
```
E0801 01:51:47.354743 20592 [main] fbcode/eden/mononoke/cmdlib/mononoke_app/src/app.rs:218] Execution error: gitimport failed

Caused by:
    0: Receiver dropped while sending Vec<(bonsai_id, git_sha1)>
    1: channel closed
Error: Execution failed
```

The errors from the finalizer thread don't get written to the logs.

This makes debugging such situations guess-work.

Let's show what's going on.

Reviewed By: singhsrb

Differential Revision: D60580947

fbshipit-source-id: 99b4b212140e1455d539bd19e0d03bc12eceb9e8