`eden shutdown` now sends SIGKILL if the shutdown() Thrift request fails to terminate Eden.
Summary:
In practice, we have seen cases where `eden shutdown` does not succeed within
15 seconds (the default timeout), and then we see the following message printed
to the console:

    error: sent shutdown request, but edenfs did not exit within 15.0 seconds

Sometimes we end up in a state where the Thrift server has successfully shutdown
but the `edenfs` process is still running. Because `eden health` is implemented
using a Thrift call, it reports that `edenfs` is not running even though it
still is. This is confusing because a subsequent `eden daemon` request will
likely fail with something like:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  another instance of Eden appears to be running for /home/mbolin/local/.eden
```

To address this, we make `eden shutdown` more aggressive in killing `edenfs`
by sending `SIGKILL`.

Follow-up work:
- Make Eden's shutdown process more robust so that `SIGKILL` is rarely, if ever,
  necessary.
- Store the PID of the `edenfs` process in the lock file so that Eden does not
  rely upon the Thrift server to be running in order to check whether the
  `edenfs` process is running.

Reviewed By: wez

Differential Revision: D6080929

fbshipit-source-id: 462a6ec506cdb6a51211d2c64b777eadbcee9fc1