pyworker: Sometimes Windows now removes the file (?)
Summary:
I got a test failure that bisected to D72617052 (the update from Rust 1.85.0 to 1.86.0).

https://www.internalfb.com/intern/test/562950064976076

```lang=text,counterexample
thread 'tests::test_remove_while_mapped' panicked at fbcode\eden\scm\saplingnative\bindings\modules\pyworker\src\lib.rs:696:13:
assertion `left == right` failed
  left: 0
 right: 1
stack backtrace:
   0: std::panicking::begin_panic_handler
             at D:\xplat\rust\toolchain\sysroot\1.86.0\library\std\src\panicking.rs:695
   1: core::panicking::panic_fmt
             at D:\xplat\rust\toolchain\sysroot\1.86.0\library\core\src\panicking.rs:75
   2: core::panicking::assert_failed_inner
             at D:\xplat\rust\toolchain\sysroot\1.86.0\library\core\src\panicking.rs:420
   3: core::panicking::assert_failed<usize,usize>
             at D:\xplat\rust\toolchain\sysroot\1.86.0\library\core\src\panicking.rs:380
   4: pyworker::tests::test_remove_while_mapped
             at D:\fbcode\eden\scm\saplingnative\bindings\modules\pyworker\src\lib.rs:696
   5: pyworker::tests::test_remove_while_mapped::closure$0
             at D:\fbcode\eden\scm\saplingnative\bindings\modules\pyworker\src\lib.rs:680
   6: core::ops::function::FnOnce::call_once<pyworker::tests::test_remove_while_mapped::closure_env$0,tuple$<> >
             at D:\xplat\rust\toolchain\sysroot\1.86.0\library\core\src\ops\function.rs:250
   7: core::ops::function::FnOnce::call_once
             at D:\xplat\rust\toolchain\sysroot\1.86.0\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I don't fully understand the test, but maybe neither did the original author 5 years ago, based on that comment. I was not able to reproduce the failure; for me the `read_dir(...).count()` still ends up being 1, not 0.

Reviewed By: capickett

Differential Revision: D72891575

fbshipit-source-id: 10ad5c61d7bd3f7d126dcc4c114acbbb5220164b