integration: try to fix changes_test.py
Summary:
Use regex instead of Windows UNC path. Trying to fix below failure:

```
AssertionError: 'Inva[40 chars]ount \\\\?\\C:\\cygwin\\data\\sandcastle\\temp[43 chars]main' != 'Inva[40 chars]ount C:\\cygwin\\data\\sandcastle\\temp\\eden_[36 chars]main'
- Invalid root path "this_path_is_a_file" in mount \\?\C:\cygwin\data\sandcastle\temp\eden_test.u76h8ft_\tmp6ryu9ac9\mounts\main
?                                                  ----
+ Invalid root path "this_path_is_a_file" in mount C:\cygwin\data\sandcastle\temp\eden_test.u76h8ft_\tmp6ryu9ac9\mounts\main
```

Reviewed By: jdelliot

Differential Revision: D73197091

fbshipit-source-id: 3306a0484da73bd7784bfe81f2ebfdd66ecc8d66