Fix crash in 'eden stop' on Thrift timeout
Summary:
If --config-dir was not specified when running 'eden stop', and edenfs is unresponsive, StopCmd.run calls `check_health_using_lockfile(None)`. This violates check_health_using_lockfile's contract because its argument must be a non-null `str`. The result is that 'eden stop' fails:

```
$ eden stop
warning: edenfs is not responding: Socket read failed: timed out
Traceback (most recent call last):
  File "[snip]/thrift/transport/TSocket.py", line 298, in read
    buff = self.handle.recv(sz)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[snip]/eden/cli/main.py", line 1221, in run
    pid = client.getPid()
[snip]
  File "[snip]/thrift/transport/TSocket.py", line 305, in read
    message='Socket read failed: {}'.format(str(e))
thrift.transport.TTransport.TTransportException: Socket read failed: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
[snip]
  File "[snip]/eden/cli/main.py", line 1231, in run
    pid = check_health_using_lockfile(args.config_dir).pid
  File "[snip]/eden/cli/util.py", line 104, in check_health_using_lockfile
    lockfile = os.path.join(config_dir, LOCK_FILE)
  File "[snip]/posixpath.py", line 78, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Make 'eden stop' use the default config directory if --config-dir was not specified.

This issue was not caught by automated tests because they specify --config-dir explicitly.

This issue was not caught by type checkers because the type of argparse.Namespace's attrs unify with any type (including `str`).

Reviewed By: simpkins

Differential Revision: D13568405

fbshipit-source-id: 395aad7e3a80b91fec05969b648a51939281ffec