localrepo: improve edenapi None error reporting
Summary:
Previously the None edenapi error isn't great for understanding what's going on:

  File "edenscm/mercurial/changelog2.py", line 123, in _openhybrid
    inner = bindings.dag.commits.openhybrid(
  TypeError: Expected type that converts to client but received NoneType

Let's make edenapi non-nullable by default, with nicer error messages, and make
places using the nullable edenapi opt-in explicitly.

Example errors:

  % lhg sl --config edenapi.url=
  abort: edenapi is required but disabled by missing edenapi.url config

  % lhg sl --config edenapi.enable=
  abort: edenapi is required but disabled by edenapi.enable being empty

  % lhg sl --config paths.default=/tmp
  abort: edenapi is required but disabled by paths.default being 'file:'

  % lhg sl --config paths.default=ssh://x --config ui.ssh=dummyssh
  abort: edenapi is required but disabled by paths.default being 'ssh:' and dummyssh in use

Reviewed By: kulshrax

Differential Revision: D29462258

fbshipit-source-id: 84fab5a7cce837c52ccb8108d1f4fe44ef2b6d1e