Back out "Move the async_requests Thrift spec out of megarepo_api"
Summary:
Original commit changeset: 538b3b20902c

Original Phabricator Diff: D61848170

Tasks are crashlooping after a release attempt: https://www.internalfb.com/onedetection/alert?alert_id=tsp_global%2Fmononoke%2Fmegarepo_async_requests_worker%2F2%40%23%24tw.unintended_task_restarts.sum.60%40%23%24mononoke%3A%20task%20is%20crashlooping

Error: P1557620544

It's probably because D61848170 changes thrift files and the client (newadmin) isn't deployed together with the server (mononoke/megarepo_async_requests_worker)

Reviewed By: andreacampi

Differential Revision: D62020463

fbshipit-source-id: 131d29ea91063a0a37080f296d882cafe1583d3e