types: remove stdlib conflicting module
Summary:
`types` conflicts with stdlib `types`. This prevents running doctests like:

  hg debugruntest revsetlang.py

Given its content is just the `ui` type, let's migrate its users to fully
qualified type `edenscm.ui.ui` explicitly.

Before:

  % lrt revsetlang.py
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib64/python3.8/multiprocessing/__init__.py", line 16, in <module>
      from . import context
    File "/usr/lib64/python3.8/multiprocessing/context.py", line 5, in <module>
      from . import process
    File "/usr/lib64/python3.8/multiprocessing/process.py", line 19, in <module>
      import signal
    File "/usr/lib64/python3.8/signal.py", line 4, in <module>
      from enum import IntEnum as _IntEnum
    File "/usr/lib64/python3.8/enum.py", line 2, in <module>
      from types import MappingProxyType, DynamicClassAttribute
    File "/data/users/quark/fbsource/fbcode/eden/scm/edenscm/types.py", line 16, in <module>
      from .ui import ui
  ImportError: attempted relative import with no known parent package
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib64/python3.8/multiprocessing/__init__.py", line 16, in <module>
      from . import context
    File "/usr/lib64/python3.8/multiprocessing/context.py", line 5, in <module>
      from . import process
    File "/usr/lib64/python3.8/multiprocessing/process.py", line 19, in <module>
      import signal
    File "/usr/lib64/python3.8/signal.py", line 4, in <module>
      from enum import IntEnum as _IntEnum
    File "/usr/lib64/python3.8/enum.py", line 2, in <module>
      from types import MappingProxyType, DynamicClassAttribute
    File "/data/users/quark/fbsource/fbcode/eden/scm/edenscm/types.py", line 16, in <module>
      from .ui import ui
  ImportError: attempted relative import with no known parent package
  # Ran 0 tests, 0 skipped, 0 failed.

After:

  % lrt revsetlang.py
  # Ran 1 tests, 0 skipped, 0 failed.

Reviewed By: muirdm

Differential Revision: D43383304

fbshipit-source-id: 1b30303046cd42ab730734f147ab51530b1916b3