eden/fs/utils/test/ImmediateFutureTest.cpp: fix platform010-exposed build errors
Summary:
We should all be migrating to platform010, for the improved performance of its
generated code and for its improved diagnostics/portability.

add an explicit constructor, now required for C++20, see https://en.cppreference.com/w/cpp/language/default_constructor

This avoids the following errors:

  eden/fs/utils/test/ImmediateFutureTest.cpp:335:17: error: no matching constructor for initialization of 'Uncopyable'

# Context:
The cost of delaying a platform upgrade is now estimated at about $3M/week.
For the preceding one, it was measured at [**$1M/week**](https://fburl.com/jfmpsqmy).

Differential Revision: D32250064

fbshipit-source-id: 8c6990489cafb09629c03e56bdbae92395d6f85f