rage: fix hgcmd for sub-command and flags with `-`
Summary:
Fix issues caused by D35302972 (https://github.com/facebookexperimental/eden/commit/e8fdef2f4b0120bbf1e864bf0b974dd912965f6c):

  hg cloud status: (0.04 s)
  ---------------------------
  Traceback (most recent call last):
    File "/opt/fb/mercurial/edenscm/mercurial/cmdutil.py", line 873, in findsubcmd
      aliases, entry = findcmd(cmd, table)
      # cmd = 'cloud status'
    File "/opt/fb/mercurial/edenscm/mercurial/cmdutil.py", line 868, in findcmd
      raise error.UnknownCommand(cmd)
      # cmd = 'cloud status'
  edenscm.mercurial.error.UnknownCommand: cloud status
  unknown command 'cloud status'
  (use 'hg help' to get help)
  [255]

  hg bookmarks --list-subscriptions: (0.03 s)
  ---------------------------
  Traceback (most recent call last):
  Traceback (most recent call last):
    File "/opt/fb/mercurial/edenscm/mercurial/dispatch.py", line 873, in _parse
      args, cmdoptions = cliparser.parsecommand(fullargs, c)
  cliparser.OptionNotRecognized: ('option --list_subscriptions not recognized', '--list_subscriptions')

  During handling of the above exception, another exception occurred:

  edenscm.mercurial.error.CommandError: ('bookmarks', 'option --list_subscriptions not recognized')
  hg bookmarks: option --list_subscriptions not recognized
  (use 'hg bookmarks -h' to get help)
  [255]

Differential Revision: D35595560

fbshipit-source-id: bdbfa6f917c70e4f71399ecfafabdbc80ca3403e