Add additional sleeps in notify_test to prevent setup folder creation from appearing in subscription stream
Summary:
Due to how folder/file creation works on projfs, there may be unexpected entries that show up in the test subscription stream before the expected values, which may cause the test to fail.

Add additional sleeps after creating setup folders to prevent the above from happening

eg:
AssertionError: False is not true : changes: [{'SmallChange': {'Added': {'file_type': 'Dir', 'path': [46, 101, 100, 101, 110, 102, 115, 45, 110, 111, 116, 105, 102, 105, 99, 97, 116, 105, 111, 110, 115, 45, 115, 116, 97, 116, 101]}}}]
(.edenfs-notifications-state)

Reviewed By: muirdm

Differential Revision: D86894088

fbshipit-source-id: e52793c43ba3e20777fabc77306cfde5544fe36a