getdeps: avoid using fmt::format with MissType enum
Summary:
getdeps fails with the following error:

```
/data/users/helsel/scratch/homeZhelselZlocalZfbsource/fbcode_builder_getdeps/installed/fmt-P3XE1sYNqr_xAI-LOfARL5-t0-J79n2DUfI08Mv6Y2Q/include/fmt/base.h: In instantiation of ‘constexpr fmt::v11::detail::value<Context> fmt::v11::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v11::context; T = const facebook::eden::FetchMiss::MissType; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/data/users/helsel/scratch/homeZhelselZlocalZfbsource/fbcode_builder_getdeps/installed/fmt-P3XE1sYNqr_xAI-LOfARL5-t0-J79n2DUfI08Mv6Y2Q/include/fmt/base.h:2018:74:   required from ‘constexpr fmt::v11::detail::format_arg_store<Context, NUM_ARGS, 0, DESC> fmt::v11::make_format_args(T& ...) [with Context = fmt::v11::context; T = {const facebook::eden::FetchMiss::MissType}; long unsigned int NUM_ARGS = 1; long unsigned int NUM_NAMED_ARGS = 0; long long unsigned int DESC = 15; typename std::enable_if<(NUM_NAMED_ARGS == 0), int>::type <anonymous> = 0]’
/data/users/helsel/scratch/homeZhelselZlocalZfbsource/fbcode_builder_getdeps/installed/fmt-P3XE1sYNqr_xAI-LOfARL5-t0-J79n2DUfI08Mv6Y2Q/include/fmt/format.h:4365:44:   required from ‘std::string fmt::v11::format(fmt::v11::format_string<T ...>, T&& ...) [with T = {const facebook::eden::FetchMiss::MissType&}; std::string = std::__cxx11::basic_string<char>; fmt::v11::format_string<T ...> = fmt::v11::basic_format_string<char, const facebook::eden::FetchMiss::MissType&>]’
/data/users/helsel/scratch/homeZhelselZlocalZfbsource/fbcode_builder_getdeps/shipit/eden/eden/fs/telemetry/LogEvent.h:419:41:   required from here
/data/users/helsel/scratch/homeZhelselZlocalZfbsource/fbcode_builder_getdeps/installed/fmt-P3XE1sYNqr_xAI-LOfARL5-t0-J79n2DUfI08Mv6Y2Q/include/fmt/base.h:1641:63: error: ‘fmt::v11::detail::type_is_unformattable_for<const facebook::eden::FetchMiss::MissType, char> _’ has incomplete type
 1641 |     type_is_unformattable_for<T, typename Context::char_type> _;
```

I couldn't find a way to use a `formatter` for this change, so added a `missTypeToString` method

Reviewed By: jdelliot

Differential Revision: D62392710

fbshipit-source-id: 197eb1b1f1e346f92d31ac8a181ab7d19e2958ef