python-modules: include all stdlib pure modules
Summary:
Include all stdlib modules so it's harder to miss dependencies, for example:

  ~/hg % ./sl log -r .
  Traceback (most recent call last):
    File "static:sapling", line 62, in run
      from . import dispatch
    File "static:sapling.dispatch", line 18, in <module>
      import pdb
    File "/home/quark/src/cpython-3.12/Lib/pdb.py", line 77, in <module>
      import code
    File "/home/quark/src/cpython-3.12/Lib/code.py", line 10, in <module>
      from codeop import CommandCompiler, compile_command
  ModuleNotFoundError: No module named 'codeop'

Binary size increased 7MB, which seems okay given the main binary is
typically hundreds of MBs.

Reviewed By: muirdm

Differential Revision: D75609446

fbshipit-source-id: 9d50c31c7041e943108a428b954195bafa6f479a