crdump: fix import error caused by PYTHONLAZYIMPORTSALL
Summary:
Python 3.12's lazy imports are stricter - they only load what's explicitly needed,
and submodule attributes aren't available unless explicitly imported.

This diff makes crdump explicitly import the commitcloud modules and makes it
compatible with both lazy and non-lazy imports.

Context:

```
$ PYTHONLAZYIMPORTSALL=1 sl dbsh -c 'print(sapling.ext.commitcloud.upload)'
Traceback (most recent call last):
  File "static:sapling.ext.debugshell", line 169, in _exec
    exec(code, env, env)
  File "debugshell:script", line 1, in <module>
    print(sapling.ext.commitcloud.upload)
AttributeError: module 'sapling.ext.commitcloud' has no attribute 'upload'
```

Reviewed By: muirdm

Differential Revision: D89811508

fbshipit-source-id: 10af4eee00e9ebcfbd0af8ec638972cc99d01be4