tests: disable inprocess-hg for test-addremove-similar.t
Summary:
This test fails on Windows when run under buck with errors like:

```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: ...
```

Disable in-process hg to avoid files being kept open.

Reviewed By: zzl0

Differential Revision: D48405408

fbshipit-source-id: 740d895b6a80fa68fc15805555b20142736f5f64