watchmanclient: fix undefined compat.PYTHON3
Summary:
Fix issue:

  AttributeError: module 'edenscm.ext.extlib.pywatchman.compat' has no attribute 'PYTHON3'

in various tests caused by D44715340.

Reviewed By: sggutier

Differential Revision: D45321822

fbshipit-source-id: 49025b54b04b819804be58ee0265d2530b67de66