getdeps: format folly::ByteRange as folly::StringPiece in SaplingBackingStore
Summary:
getdeps fails with the following error:

```
/data/users/helsel/scratch/homeZhelselZlocalZfbsource/fbcode_builder_getdeps/shipit/eden/eden/fs/store/hg/SaplingBackingStore.cpp:913:7:   required from ‘std::pair<std::map<folly::Range<const unsigned char*>, std::pair<std::vector<std::shared_ptr<facebook::eden::SaplingImportRequest> >, facebook::eden::RequestMetricsScope> >, std::vector<sapling::SaplingRequest> > facebook::eden::SaplingBackingStore::prepareRequests(const ImportRequestsList&, const facebook::eden::SaplingBackingStore::SaplingImportObject&) [with T = facebook::eden::SaplingImportRequest::BaseImport<std::shared_ptr<const facebook::eden::Blob> >; facebook::eden::SaplingBackingStore::ImportRequestsList = std::vector<std::shared_ptr<facebook::eden::SaplingImportRequest> >]’
/data/users/helsel/scratch/homeZhelselZlocalZfbsource/fbcode_builder_getdeps/shipit/eden/eden/fs/store/hg/SaplingBackingStore.cpp:662:76:   required from here
/data/users/helsel/scratch/homeZhelselZlocalZfbsource/fbcode_builder_getdeps/installed/fmt-P3XE1sYNqr_xAI-LOfARL5-t0-J79n2DUfI08Mv6Y2Q/include/fmt/base.h:1627:17: error: static assertion failed: Mixing character types is disallowed.
 1627 |   static_assert(formattable_char, "Mixing character types is disallowed.");
      |                 ^~~~~~~~~~~~~~~~
```

getdeps doesnt like using both a `folly::StringPiece` and a `folly::ByteRage`. This diff converts the `folly::ByteRange` to a `folly::StringPiece` https://fburl.com/code/vc4cp6vi

Reviewed By: kavehahmadi60

Differential Revision: D62419376

fbshipit-source-id: 252d973708fba9f59dc7d4c3d856afcdce187e8c