pyrevisionstore: raise KeyboardInterrupt instead of RuntimeError for Ctrl+C
Summary:
`cpython_ext::PyErr` can round-trip a Python error seamlessly. Use it so we
don't translate `KeyboardInterrupt` into `RutimeError` incorrectly.

Before this change:

  % hg status -c 'glob:skycastle/src/test/resources**'
  ^C
    File "/usr/lib64/python2.7/site-packages/edenscm/mercurial/dirstate.py", line 1025, in status
      for fn in pctx.manifest().matches(match):
  RuntimeError: Python Error: PyErr { ptype: <type 'exceptions.KeyboardInterrupt'>, pvalue: None, ptraceback: Some(<traceback object at 0x7f5cedec6d40>) }

After this change:

  % ~/hg/hg status -c 'glob:skycastle/src/test/resources**'  --traceback --debugger
  ...
  ^C
    File "/data/users/quark/fbsource/fbcode/scm/hg/edenscm/mercurial/dirstate.py", line 1025, in status
    for fn in pctx.manifest().matches(match):
    File "/data/users/quark/fbsource/fbcode/scm/hg/edenscm/hgext/remotefilelog/contentstore.py", line 155, in prefetch
      store.prefetch(keys)
    File "/data/users/quark/fbsource/fbcode/scm/hg/edenscm/hgext/treemanifest/__init__.py", line 2613, in prefetch
      self._repo._httpgettrees(keys)
    File "/data/users/quark/fbsource/fbcode/scm/hg/edenscm/hgext/treemanifest/__init__.py", line 642, in _httpgettrees
      stats = self.edenapi.get_trees(keys, dpack, progcallback)
    File "/data/users/quark/fbsource/fbcode/scm/hg/edenscm/hgext/remotefilelog/edenapi.py", line 192, in wrapped
      thread.join(1)
    File "/usr/lib64/python2.7/threading.py", line 962, in join
      self.__block.wait(delay, balancing)
    File "/usr/lib64/python2.7/threading.py", line 362, in wait
      _sleep(delay)
  KeyboardInterrupt
  ipdb>

Reviewed By: xavierd

Differential Revision: D18329939

fbshipit-source-id: 45a8e598279209df56ed90589fbfbd4336ab5ecc