eden: make EdenThriftClient reloadable
Summary:
The current code is unsafe to execute twice (in rare situations):

    orig_pack = struct.pack
    def wrap_pack(...):
        return orig_pack(...)  # will lookup 'orig_pack' from globals()
    struct.pack = wrap_pack

    # If executed again
    orig_pack = struct.pack   # globals()['orig_pack'] = globals()['wrap_pack']
    def wrap_pack(...):       # globals()['wrap_pack'] = wrap_pack
        return orig_pack(...) # stack overflow (!)
    struct.pack = wrap_pack

This issue can be demonstrated in `hg debugshell`:

    In [1]: import edenscm.mercurial.EdenThriftClient

    In [2]: import struct

    In [3]: struct.unpack('','')
    Out[3]: ()

    In [4]: reload( edenscm.mercurial.EdenThriftClient)
    Out[4]: <module 'edenscm.mercurial.EdenThriftClient' from '/usr/lib64/python2.7/site-packages/edenscm/mercurial/EdenThriftClient.pyc'>

    In [5]: struct.unpack('','')

    RuntimeErrorTraceback (most recent call last)
    /usr/lib64/python2.7/site-packages/edenscm/hgext/debugshell.pyc in <module>()
    ----> 1 struct.unpack('','')

    /usr/lib64/python2.7/site-packages/edenscm/mercurial/EdenThriftClient.pyc in wrap_unpack(fmt, data)
         43         if isinstance(fmt, unicode):  # noqa: F821
         44             fmt = fmt.encode("utf-8")
    ---> 45         return orig_unpack(fmt, data)
         46
         47     struct.pack = wrap_pack

    ... last 1 frames repeated, from the frame below ...

    /usr/lib64/python2.7/site-packages/edenscm/mercurial/EdenThriftClient.pyc in wrap_unpack(fmt, data)
         43         if isinstance(fmt, unicode):  # noqa: F821
         44             fmt = fmt.encode("utf-8")
    ---> 45         return orig_unpack(fmt, data)
         46
         47     struct.pack = wrap_pack

    RuntimeError: maximum recursion depth exceeded while calling a Python object

Fix it by avoiding looking up variables from globals().

This was discovered when I was experimenting with other stuff related to the
Python import logic. I also fixed the import logic so it can handle this case.

Reviewed By: fanzeyi

Differential Revision: D18087097

fbshipit-source-id: 472d80260ddb3d2c795b2ede5d5f1af19f3e6f2f