build: upgrade Python version for Windows
Summary:
* The [Py_TPFLAGS_DISALLOW_INSTANTIATION](https://github.com/python/cpython/commit/3bb09947ec4837de75532e21dd4bd25db0a1f1b7) const was added in Python 3.10, so this diff upgraded the Python version.

```
  ../../../../sapling/cext/../../lib/third-party/windows-curses\_curses_panel.c(523): error C2065: 'Py_TPFLAGS_DISALLOW_INSTANTIATION': undeclared identifier
  ../../../../sapling/cext/../../lib/third-party/windows-curses\_curses_panel.c(520): error C2099: initializer is not a constant
  ../../../../sapling/cext/../../lib/third-party/windows-curses\_curses_panel.c(524): warning C4047: 'initializing': 'unsigned int' differs in levels of indirection from 'PyType_Slot *'
  ../../../../sapling/cext/../../lib/third-party/windows-curses\_curses_panel.c(654): warning C4013: 'PyType_FromModuleAndSpec' undefined; assuming extern returning int
  ../../../../sapling/cext/../../lib/third-party/windows-curses\_curses_panel.c(655): warning C4312: 'type cast': conversion from 'int' to 'PyTypeObject *' of greater size
  ../../../../sapling/cext/../../lib/third-party/windows-curses\_curses_panel.c(660): warning C4013: 'PyModule_AddType' undefined; assuming extern returning int
  ../../../../sapling/cext/../../lib/third-party/windows-curses\_curses_panel.c(701): warning C4152: nonstandard extension, function/data pointer conversion in expression
  exit code: 2
```
* This diff also stop fetching `windows_curses` since we have venderred it as third-party

Reviewed By: muirdm

Differential Revision: D51128035

fbshipit-source-id: 148be82688be9fa89d14ebc2d56b671e20fa4ce0