watchmanclient: drop "version =" in Cargo.toml
Summary:
`path = ...` is enough. This should resolve the following build issues:

  error: failed to select a version for the requirement `serde_bser = "^0.1.0"`
    candidate versions found which didn't match: 0.2.0
    location searched: ...
  required by package `watchman_client v0.1.0 (...)
      ... which is depended on by `hg_watchman_client v0.1.0 (...)`

Reviewed By: lukaspiatkowski

Differential Revision: D18738176

fbshipit-source-id: 725840895a8e988b35000a48cf92018b14cb4dee