setup: teach shutil.rmtree to handle read-only files on Windows
Summary:
While running `make local` on Windows, I got:

  running build_rust_ext
  downloading vendored crates 'tp2-crates-io'
  [crates-io.py] downloading vendored crates archive from LFS
  [crates-io.py] removing outdated vendor directory
  Traceback (most recent call last):
    File "fbcode\tools\lfs\crates-io.py", line 101, in <module>
      download()
    File "fbcode\tools\lfs\crates-io.py", line 69, in download
      shutil.rmtree(VENDOR_DIRNAME)
    File "fbcode\scm\hg\build\hg-python\lib\shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "fbcode\scm\hg\build\hg-python\lib\shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "fbcode\scm\hg\build\hg-python\lib\shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "fbcode\scm\hg\build\hg-python\lib\shutil.py", line 252, in rmtree
      onerror(os.remove, fullname, sys.exc_info())
    File "fbcode\scm\hg\build\hg-python\lib\shutil.py", line 250, in rmtree
      os.remove(fullname)
  WindowsError: [Error 5] Access is denied: 'vendor\\lalrpop\\src\\parser\\lrgrammar.rs'
  error: download of Rust vendored crates 'tp2-crates-io' failed
  make.exe: *** [local] Error 1

This is caused by the file being deleted has "read-only" attribute set on Windows.
Fix it by removing the read-only attribute automatically.
As we're here, also change `crates-io.py` to do the same thing as it's used by `setup.py`.

Reviewed By: ikostia

Differential Revision: D13413081

fbshipit-source-id: b10c44fd152a61c021edf6a8d86cb82a339f366f