fix error chain propagation across ffi
Summary:
Use a custom error type CxxAnyhowError that propagates the compact "{:#}" format for the Display trait (which is what cxx passes to C++). This way the full error chain will show up.

This should help see what the actual error is for failures like:
```
thrift.python.exceptions.ApplicationError: (<ApplicationErrorType.UNKNOWN: 0>, 'rust::cxxbridge1::Error: failed to expand redirection target path')
```

There are more errors in the chain - we just aren't seeing them.

Reviewed By: MichaelCuevas

Differential Revision: D96048063

fbshipit-source-id: 1e4f61c4e0313f0bd860641015bc048ff93fb9eb