Remove stylex errors in test output
Summary:
jest test output had a lot of lines like:
```
ts-jest[ts-compiler] (WARN) src/TopLevelAlert.tsx:89:30 - error TS2554: Expected 0 arguments, but got 1.

 89 const styles = stylex.create({
                                 ~
 90   alertContainer: {
    ~~~~~~~~~~~~~~~~~~~
...
122   UBN: {backgroundColor: colors.purple},
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
123 });
    ~
```

This is because our mock for stylex had no types for the parameters. Just updating our mock with unused arg defs fixes this.

Reviewed By: quark-zju

Differential Revision: D54424188

fbshipit-source-id: 179ff36db7e6f2f563cdbd0bcf248db79126e86c