mercurialshim: remove ctypes dependency
Summary:
This makes it friendly to run on systems with Python built from source where
the `ffi` library cannot be built (due to lack of headers) and `_ctypes` cannot
be imported:

  $ ./sl --help
  Traceback (most recent call last):
    File "static:sapling", line 86, in run
      dispatch.run(args, fin, fout, ferr, ctx, skipprehooks)
    File "static:sapling.dispatch", line 156, in run
      sys.meta_path.insert(0, mercurialshim.MercurialImporter())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "static:importlib.util", line 262, in __getattribute__
      __spec__.loader.exec_module(self)
    File "static:sapling.mercurialshim", line 8, in <module>
      from ctypes import ArgumentError
    File "static:importlib.util", line 262, in __getattribute__
      __spec__.loader.exec_module(self)
    File "static:ctypes", line 8, in <module>
      from _ctypes import Union, Structure, Array
  ModuleNotFoundError: No module named '_ctypes'

Reviewed By: muirdm

Differential Revision: D59647360

fbshipit-source-id: 72187bfdd2e9daa928fe4d542af4e433b69aac0a