Remove unused var
Summary:
Pika 16.3 / LLVM-19 has this as a failure now:

```
fbcode/eden/fs/inodes/TreeInode.cpp:3943:20: error: variable 'nfsdChannel' set but not used [-Werror,-Wunused-but-set-variable]
 3943 |   } else if (auto* nfsdChannel = getMount()->getNfsdChannel()) {
      |                    ^
1 error generated.
```

Reviewed By: MichaelCuevas

Differential Revision: D70368995

fbshipit-source-id: 766582cdd9132fca48b04db4148a4bb5f88cdc5e