github: use newer image to run tests
Summary:
Currently, the tests are failing with:

    TypeError: [(...chunks)].toSorted is not a function

      328 |   // Apply the changes. Assuming there are no overlapping chunks, we apply
      329 |   // from end to start so the line numbers won't need change.
    > 330 |   const sortedChunks = [...chunks].toSorted((a, b) => b.oldEnd - a.oldEnd);
          |                                    ^
      331 |   sortedChunks.forEach(chunk => {
      332 |     // If not "selected" to amend to a commit, leave the chunk at the wdir.
      333 |     const baseRev = chunk.selectedRev ?? (wdirRev as FileRev);

It might be caused by the nodejs being too old. Let's try bumping the OS image
to see what happens.

Reviewed By: evangrayk

Differential Revision: D68189455

fbshipit-source-id: 42afb8a01275fc09f9d008364f0bed2b214d37a8