commitcloud: redirect stdin to /dev/null for background processes
Summary:
Both xavierd and I noticed that characters typed in the terminal sometimes got
eaten.  In my case, killing the background cloud sync processes solves it.

It turns out that the cloud sync erroed out like:

  ServiceError: service error: 500 ...: Mysql error 1062. Duplicate entry 'fbsource-user/quark/default-remote-fbobjc/stable' for key 'PRIMARY' to db ...

And the `cloud sync` command started ipdb, which starts eating characters :/.

D17621846 should have fixed it. Let's just make it safer by redirecting
stdin of background processes to /dev/null.

Reviewed By: xavierd

Differential Revision: D17622250

fbshipit-source-id: d804aea4aa0aeb50bba0307f93a41eb94e8529fc