du: add a bunch of context to errors
Summary:
`eden du` recently started failing for me with the following error:

  % edenfsctl.exe du
  Error: The system cannot find the file specified. (os error 2)

  Caused by:
      The system cannot find the file specified. (os error 2)

Since it's pretty much impossible to figure out what actually failed, we can't
debug this. Adding context will make it easier to debug.

Reviewed By: genevievehelsel

Differential Revision: D38997315

fbshipit-source-id: 80396366e1979916946947f4145738c6cf28fe5a