autocargo: ctp: depend on pxl instead of re-declaring its crates
Summary:
You can't run Autocargo right now, it fails with:

```
Error: File CargoTomlPath { file: PathInFbcode("configerator/structs/data_access_policies/upf/eval/Cargo.toml"), dir: PathInFbcode("configerator/structs/data_access_policies/upf/eval") } is covered by both ctp and pxl projects
```

This is affecting me (on Buck2) since some of our dependencies use Autocargo
for their Cargo.tomls and those are now missing some dependencies (notably,
`below` needs `nix`). This also affects people trying to vendor crates:

https://fb.workplace.com/groups/rust.language/permalink/7625318880849994/
https://fb.workplace.com/groups/rust.language/permalink/7577471608968055/

This diff fixes it, and regenerates Cargo.tomls as a result.

Note: I'm not sure exactly what "pxl" is, but it seems to be owned by the team working on data access so that's a better home for that crate than ctp.

Reviewed By: ahornby

Differential Revision: D33428045

fbshipit-source-id: f3feab3ae04069672040423c145c69a58445ef96