delete darkstorm from redaction tool
Summary:
Tried to do a redaction yesterday and ran into an error creating the key:
```
Error: Configuration must have darkstorm blobstore
```

Dark isolon was deprecated a little while ago: https://fb.workplace.com/groups/sourcecontrolteam/permalink/6855579047896716/

And Clara recently cleaned up some configuration from that: D59809804.

I think that broke the redaction tool.

We don't need to redact from dark isolon any more because it's not used any
more (doesn't exist, not updated?).

Should be fine to delete this then. From chatting with Clara sounds like we will
eventually need to update this to redact from AWS too but that's gonna
require some figuring out. For now delete this code so we have a working
redaction tool.

Reviewed By: gustavoavena

Differential Revision: D61239858

fbshipit-source-id: e301b26c3b1b6577dfacf8d72f4c9128b8a2d325