github: update installed deps in Dockfile
Summary:
We no longer use `cython`. `zstd-sys` uses `bindgen` now and [requires `libclang-dev`](https://rust-lang.github.io/rust-bindgen/requirements.html).

```
  thread 'main' panicked at /github/home/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bindgen-0.71.1/lib.rs:604:27:
  Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

Reviewed By: zzl0

Differential Revision: D75094355

fbshipit-source-id: b6667ce179224c8477563352a249c576402d3582