Don't include commit title in PR body
Seems redundant to include the commit title in both the PR body and title, so this strips out the title.

Had some trouble building to test this out (ran into `error[E0658]: use of unstable library feature 'stdsimd'`)