eden: fix prefetchtrees argument
Summary:
My edenfs log is filled with the following backtrace:

  Traceback (most recent call last):
    File "/opt/fb/mercurial/edenscm/mercurial/commands/eden.py", line 421, in get_tree
      self._fetch_tree_impl(path, manifest_node)
    File "/opt/fb/mercurial/edenscm/mercurial/commands/eden.py", line 671, in _fetch_tree_impl
      self.repo._prefetchtrees(path, mfnodes, [], [])
    File "/opt/fb/mercurial/edenscm/hgext/treemanifest/__init__.py", line 565, in _prefetchtrees
      return self._httpprefetchtrees(*args, **kwargs)
    File "/opt/fb/mercurial/edenscm/hgext/treemanifest/__init__.py", line 678, in _httpprefetchtrees
      self.edenapi.complete_trees(
  TypeError: Expected type that converts to PySequence but received set

And indeed, the code passes a set instead of a plain list.

Reviewed By: kmancini

Differential Revision: D26545708

fbshipit-source-id: 4164154d9cc8991b596198d9324474f646cc194c