cstore: fixup missing nullptr declaration
Summary:
this is failing the contbuild:

```
In file included from cstore/pythonutil.h:23,
                 from cstore/py-datapackstore.h:21,
                 from cstore/py-cstore.cpp:17:
cstore/../cstore/store.h: In member function  const char* ConstantStringRef::content() :
cstore/../cstore/store.h:37: error:  nullptr  was not declared in this scope
error: command 'gcc' failed with exit status 1
error: Bad exit status from /var/tmp/rpm-tmp.PjSlGE (%build)
```

Test Plan: make local

Reviewers: #mercurial, simonfar

Reviewed By: simonfar

Subscribers: mjpieters

Differential Revision: https://phabricator.intern.facebook.com/D4954802

Signature: t1:4954802:1493224431:55d7123f523c29adb5d0d97d5030fa1c6b0f4845