nodeipc: fix compatibility with chg
Summary:
For chg, it needs to pass the node channel fd explicitly.
The chg server should not use the node channel fd, and should close it.

Test script:

  # p.js
  const {spawn} = require('child_process');
  let executable = '/bin/hg';
  const args = ['dbsh', '-c', String.raw`b.nodeipc.IPC.send('foo'); ui.write("[Child] Got message: %r\n" % b.nodeipc.IPC.recv());`];
  const child = spawn(executable, args, {stdio: ['inherit', 'inherit', 'inherit', 'ipc']} );
  const responses = ['HELLO FROM PARENT 1', 'HELLO FROM PARENT 2', 'BYE'];
  child.on('message', message => {
    console.log('[Parent] Got message from child:', message);
    const response = responses.shift();
    if (response) { child.send(response); }
  });
  child.on('exit', () => { console.log('[Parent] Child process has exited'); });

Before:

  $ CHGSOCKNAME=$PWD/foo CHGDEBUG=1 node p.js
  using chg: true, because /etc/mercurial/usechg
  chg: debug: 0.000028 try connect to /home/quark/hg/lib/util/nodeipc/examples/foo-hg
  chg: debug: 0.000141 connected to foo-hg
  ...
  chg: debug: 0.007911 request runcommand, block size 96
  Traceback (most recent call last):
    File "/opt/fb/mercurial/edenscm/ext/debugshell.py", line 99, in debugshell
      exec(command, env, env)
      # command = 'b.nodeipc.IPC.send(\'foo\'); ui.write("[Child] Got message: %r\\n" % b.nodeipc.IPC.recv());'
    File "<string>", line 1, in <module>
  BrokenPipeError: [Errno 32] Broken pipe (os error 32)
  chg: debug: 0.162147 response read from channel r, size 4
  chg: debug: 0.162160 got exitcode 255
  chg: debug: 0.162181 free context buffer
  [Parent] Child process has exited

After:

  $ CHGSOCKNAME=$PWD/foo CHGDEBUG=1 HG_REAL_BIN=~/hg/hg node p.js
  using chg: true, because unix
  chg: debug: 0.000026 try connect to /home/quark/hg/lib/util/nodeipc/examples/foo-hg
  ...
  chg: debug: 0.008299 request attachio
  chg: debug: 0.008572 passing NODE_CHANNEL_FD 3
  chg: debug: 0.008870 response read from channel r, size 4
  ...
  chg: debug: 0.009038 request runcommand, block size 96
  [Parent] Got message from child: foo
  [Child] Got message: 'HELLO FROM PARENT 1'
  chg: debug: 0.163058 response read from channel r, size 4
  chg: debug: 0.163072 got exitcode 0
  chg: debug: 0.163084 free context buffer
  [Parent] Child process has exited

Reviewed By: zzl0

Differential Revision: D45011055

fbshipit-source-id: 20d59358a5203f0966b13120ee8a5e1e8585adc3