shelve: resolve unshelve crash on conflicts
Summary:
The old assumption is that new commits get rev numbers `len(repo)`,
`len(repo)+1`, `len(repo)+2`, ... That's no longer true with segmented
changelog because of the "groups" design, non-master commits would have
a much higher numbers.

The old assumption leads to crashes like:

      File "edenscm/hgext/shelve.py", line 1036, in unshelve
        return _dounshelve(ui, repo, *shelved, **opts)
      File "edenscm/hgext/shelve.py", line 1138, in _dounshelve
        shelvectx = _rebaserestoredcommit(
      File "edenscm/hgext/shelve.py", line 898, in _rebaserestoredcommit
        nodestoremove = [
      File "edenscm/hgext/shelve.py", line 899, in <listcomp>
        repo.changelog.node(rev) for rev in range(oldtiprev, len(repo))
      File "edenscm/mercurial/changelog2.py", line 348, in node
        raise IndexError("revlog index out of range")
      IndexError: revlog index out of range

The code just needs to figure out newly added commits from a previous state.
Track old and new heads to calculate that instead.

Reviewed By: DurhamG

Differential Revision: D31819056

fbshipit-source-id: 156abf2bd56a959b77ec090b8602c9621877d2c5