getdeps: call toBackingStoreString in EDEN_BUG
Summary:
getdeps fails with the following error:

```
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-FHukGLl-vQ54P4P_dMfig6Np0_gq5419Adqk0Dqpexo/include/fmt/base.h:2940:61:   required from ‘fmt::v11::remove_cvref_t<T> fmt::v11::format_to(OutputIt&&, fmt::v11::format_string<T ...>, T&& ...) [with OutputIt = std::back_insert_iterator<std::__cxx11::basic_string<char> >; T = {const facebook::eden::BackingStoreType&}; typename std::enable_if<fmt::v11::detail::is_output_iterator<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, char>::value, int>::type <anonymous> = 0; fmt::v11::remove_cvref_t<T> = std::back_insert_iterator<std::__cxx11::basic_string<char> >; fmt::v11::format_string<T ...> = fmt::v11::basic_format_string<char, const facebook::eden::BackingStoreType&>]’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/eden/eden/common/utils/Bug.h:79:19:   required from ‘facebook::eden::EdenBug&& facebook::eden::EdenBug::operator<<(const T&) && [with T = facebook::eden::BackingStoreType]’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/eden/eden/fs/service/EdenMain.cpp:97:60:   required from here
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-FHukGLl-vQ54P4P_dMfig6Np0_gq5419Adqk0Dqpexo/include/fmt/base.h:1641:63: error: ‘fmt::v11::detail::type_is_unformattable_for<const facebook::eden::BackingStoreType, char> _’ has incomplete type
 1641 |     type_is_unformattable_for<T, typename Context::char_type> _;
```

This diff calls `toBackingStoreString` to mitigate this issue.

Differential Revision: D62397045

fbshipit-source-id: 3a775857151a09baa1d0fc3d4f3947bdc7705528