Upgrade dependencies used by streampager
Summary:
Upgrade dependencies requested by https://github.com/facebook/sapling/pull/1008, with the exceptions:

- No change to `lru` and `indexmap`, because they want `hashbrown 0.15.2`,
  which fails to compile until Rust [1.84](https://github.com/rust-lang/rust/commit/56ee492a6e7a917b2b3f888e33dd52a13d3ecb64).

```
  error[E0635]: unknown feature `strict_provenance_lints`
    --> third-party/rust/vendor/hashbrown-0.15.2/src/lib.rs:24:9
     |
  24 |         strict_provenance_lints
     |         ^^^^^^^^^^^^^^^^^^^^^^^
```

- No change to `notify`. It specifies `fsevents-sys = "4.0.0"` and fails to compile:

```
  error[E0425]: cannot find function, tuple struct or tuple variant `FSEventsGetCurrentEventId` in crate `fs`
     --> third-party/rust/vendor/notify-8.0.0/src/fsevent.rs:462:40
      |
  462 |                     let event_id = fs::FSEventsGetCurrentEventId();
      |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `fs`

  (`FSEventsGetCurrentEventId` was introduced in `fsevents-sys 4.1.0`)
```

- No change to `unicode-width` because
  https://github.com/phsym/prettytable-rs/issues/165 (`prettytable-rs` does not
  pin the "good" version of `unicode-width` so `unicode-width` has to be
  globally pinned)

- No change to `bit-set` to avoid incompatible types:

```
error[E0308]: mismatched types
   --> fbcode/hphp/hack/src/hackc/emitter/opt_body.rs:287:49
    |
287 |         avl_in.union_with(&BitSet::from_bit_vec(BitVec::from_elem(nparams, true)));
    |                            -------------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `bit_vec::BitVec`, found `BitVec`
    |                            |
    |                            arguments to this function are incorrect
    |
    = note: `BitVec` and `bit_vec::BitVec` have similar names, but are actually distinct types
note: `BitVec` is defined in crate `bit_vec`
   --> third-party/rust/vendor/bit-vec-0.6.2/src/lib.rs:210:1
note: `bit_vec::BitVec` is defined in crate `bit_vec`
   --> third-party/rust/vendor/bit-vec-0.8.0/src/lib.rs:249:1
    = note: perhaps two different versions of crate `bit_vec` are being used?
note: associated function defined here
   --> third-party/rust/vendor/bit-set-0.8.0/src/lib.rs:240:12
```

- No change to `memmap2` since it seems to cause hack-www-test breakage.

Reviewed By: zzl0

Differential Revision: D69427081

fbshipit-source-id: f520721fd4b828ae46c6b2d7875fa68eaafe603e