python-modules: include modules used by sysconfig
Summary:
The assumption that `sys.stdlib_module_names` include all pure Python modules
in stdlib is false. `sysconfig` will `__import__` a module like
`_sysconfigdata__linux_x86_64-linux-gnu`, which is not listed.

Consider that case to make `sysconfig` work.

Practically, static python build on manylinux can error out like without this
change, because it relies on the `python-modules` to contain all pure stdlib
modules:

  % osl debugpython ~/Downloads/pip.pyz install ipython
  Traceback (most recent call last):
    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "/home/quark/Downloads/pip.pyz/__main__.py", line 26, in <module>
    File "<frozen runpy>", line 229, in run_module
    File "<frozen runpy>", line 88, in _run_code
    File "/home/quark/Downloads/pip.pyz/pip/__main__.py", line 22, in <module>
    File "/home/quark/Downloads/pip.pyz/pip/_internal/cli/main.py", line 10, in <module>
    File "/home/quark/Downloads/pip.pyz/pip/_internal/cli/autocompletion.py", line 9, in <module>
    File "/home/quark/Downloads/pip.pyz/pip/_internal/cli/main_parser.py", line 8, in <module>
    File "/home/quark/Downloads/pip.pyz/pip/_internal/build_env.py", line 16, in <module>
    File "/home/quark/Downloads/pip.pyz/pip/_internal/cli/spinners.py", line 9, in <module>
    File "/home/quark/Downloads/pip.pyz/pip/_internal/utils/logging.py", line 29, in <module>
    File "/home/quark/Downloads/pip.pyz/pip/_internal/utils/misc.py", line 42, in <module>
    File "/home/quark/Downloads/pip.pyz/pip/_internal/locations/__init__.py", line 14, in <module>
    File "/home/quark/Downloads/pip.pyz/pip/_internal/locations/_sysconfig.py", line 11, in <module>
    File "/home/quark/Downloads/pip.pyz/pip/_internal/locations/base.py", line 16, in <module>
    File "/opt/python/cp312-cp312/lib/python3.12/sysconfig.py", line 641, in get_path
      return get_paths(scheme, vars, expand)[name]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/python/cp312-cp312/lib/python3.12/sysconfig.py", line 631, in get_paths
      return _expand_vars(scheme, vars)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/python/cp312-cp312/lib/python3.12/sysconfig.py", line 275, in _expand_vars
      _extend_dict(vars, get_config_vars())
                         ^^^^^^^^^^^^^^^^^
    File "/opt/python/cp312-cp312/lib/python3.12/sysconfig.py", line 731, in get_config_vars
      _init_config_vars()
    File "/opt/python/cp312-cp312/lib/python3.12/sysconfig.py", line 677, in _init_config_vars
      _init_posix(_CONFIG_VARS)
    File "/opt/python/cp312-cp312/lib/python3.12/sysconfig.py", line 541, in _init_posix
      _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ModuleNotFoundError: No module named '_sysconfigdata__linux_x86_64-linux-gnu'

I checked that this is the only missing module that start with `_`. Other `_`
modules can be imported from the static python build:

  _aix_support.py
  _collections_abc.py
  _compat_pickle.py
  _compression.py
  __future__.py
  __hello__.py
  _markupbase.py
  _osx_support.py
  __phello__
  _py_abc.py
  _pydatetime.py
  _pydecimal.py
  _pyio.py
  _pylong.py
  _sitebuiltins.py
  _strptime.py
  # _sysconfigdata__linux_x86_64-linux-gnu.py
  _threading_local.py
  _weakrefset.py

Reviewed By: muirdm

Differential Revision: D76636322

fbshipit-source-id: 65a0ee5a8f3a230de5cd7e3822d381d25133d28c