cargo: attempt to unblock GitHub build
Summary:
GitHub builds are failing with the "std" feature:

  $ cargo build --manifest-path /__w/sapling/sapling/eden/scm/exec/hgmain/Cargo.toml --release --features sl_oss
  warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
  package:   /__w/sapling/sapling/eden/scm/exec/hgmain/Cargo.toml
  workspace: /__w/sapling/sapling/eden/scm/Cargo.toml
  warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
  package:   /__w/sapling/sapling/eden/scm/lib/virtual-repo/virtual-tree/Cargo.toml
  workspace: /__w/sapling/sapling/eden/scm/Cargo.toml
  warning: /__w/sapling/sapling/eden/scm/lib/third-party/streampager/Cargo.toml: `edition` is set on library `streampager` which is deprecated
  warning: /__w/sapling/sapling/eden/scm/lib/third-party/conch-parser/Cargo.toml: `edition` is set on library `conch_parser` which is deprecated
  warning: /__w/sapling/sapling/eden/scm/lib/third-party/webview-sys/Cargo.toml: `edition` is set on library `webview_sys` which is deprecated
  warning: /__w/sapling/sapling/eden/scm/lib/slex/Cargo.toml: file `/__w/sapling/sapling/eden/scm/lib/slex/benches/executor.rs` found to be present in multiple build targets:
    * `bench` target `executor`
    * `bench` target `executor_benches`
      Updating git repository `https://github.com/markbt/abomonation`
      Updating crates.io index
      Updating git repository `https://github.com/facebookexperimental/rust-shed.git`
      Updating git repository `https://github.com/facebook/watchman.git`
      Updating git repository `https://github.com/facebook/fb303.git`
      Updating git repository `https://github.com/facebook/fbthrift.git`
  error: failed to select a version for `wezterm-dynamic`.
      ... required by package `sapling-io v0.1.0 (/__w/sapling/sapling/eden/scm/lib/io)`
      ... which satisfies path dependency `sapling-io` of package `sapling-clidispatch v0.1.0 (/__w/sapling/sapling/eden/scm/lib/clidispatch)`
      ... which satisfies path dependency `sapling-clidispatch` of package `hgmain v0.1.0 (/__w/sapling/sapling/eden/scm/exec/hgmain)`
  versions that meet the requirements `^0.2.1` are: 0.2.1

  package `sapling-io` depends on `wezterm-dynamic` with feature `std` but `wezterm-dynamic` does not have that feature.

This will unfortunately break fbsource cargo build. I pinged wez on
`wezterm:matrix.org` and hope we can get a 0.24 termwiz release to fix this.

Reviewed By: zzl0

Differential Revision: D115614865

fbshipit-source-id: 54ba5c8a452a2d6faf74b0b2aea9b61b5d30a6c7