Set higher retries and retry interval for ShardManager client initialization
Summary:
Recently, we encountered a shardmanager issue which resulted in the sharded task crashlooping for nearly an hour. The relevant error message was:
```
E0303 09:44:16.438213    80 [main] fbcode/eden/mononoke/cmdlib/mononoke_app/src/app.rs:232] Execution error: A C++ exception occurred

Caused by:

    Failed to initialize ShardManager client

Error: Execution failed
```

The ShardManager team [advocated](https://fb.workplace.com/groups/sm.users/posts/3309305459203824/?comment_id=3309767809157589) setting a more resistant SM client initialization configuration and this diff follows that advice.

Reviewed By: YousefSalama

Differential Revision: D70561956

fbshipit-source-id: fd638c22bdcf51f22cbeb7b37fd7304cfee73a50