Fix boolean command-line flags to cas sync
Summary:
D73596162 migrated cas sync to clap4 but slightly changed the syntax of boolean flags:

```
error: a value is required for '--log-to-scuba <LOG_TO_SCUBA>' but none was supplied
  [possible values: true, false]
For more information, try '--help'.
```

This cause [Conveyor](https://www.internalfb.com/svc/services/mononoke/cas_sync/conveyor/mononoke/cas_sync/releases) to fail (for a few weeks now): the canary fails immediately.

I *could* just update the tw spec, but our services and CLIs almost never use `Option<bool>`, because we rarely need to distinguish between the default value or a truly unset option.

Reviewed By: lmvasquezg

Differential Revision: D74585222

fbshipit-source-id: 202357b4b4c11be9fae900b6473bf67eb31e5beb