hiddenerror: do not wrap changectx
Instead of wrapping changectx constructor, there is a cleaner way to change
the hidden error message. changectx is constructed frequently so this change
also has perf benefit. It saves about 5ms when running `sl` on fbsource and
it also makes traceprof able to expand changectx.__init__ call graph.

Differential Revision: https://phab.mercurial-scm.org/D1445