website: fix the deploy yaml
Summary:
the yaml file was broken by D47035733 for 5 months, let's just remove the pull-request events.

```
Error: .github#L1
Invalid type for `on`
```

e.g. https://github.com/facebook/sapling/actions/runs/6863386967

Reviewed By: sggutier

Differential Revision: D51292816

fbshipit-source-id: 04295cf76ebe37b939e4500172a795b5996a6a2f