eden/fs/service/EdenServiceHandler.cpp: adapt to C++20
Summary:
Cast EDEN_MICRO to something fmt::format can handle: char* (from std::basic_string<char8_t>); but that means this is no longer a literal, so cannot concat. Move to its own fmt argument.

This avoids the following errors:

  eden/fs/service/EdenServiceHandler.cpp:227:60: error: invalid operands to binary expression ('basic_ostream<char>' and 'std::basic_string<char8_t>')

Differential Revision: D32486517

fbshipit-source-id: c799bdd73be1b46cc938b2076ebc78d0bdb3dded