scmdaemon: use io::Write on osx
Summary:
D9030136 removed the `use` statement and broke OSX build:

```
   Compiling scm_daemon v0.1.0 (file:///.../exec/scm_daemon)
error[E0599]: no method named `write_fmt` found for type `std::fs::File` in the current scope
  --> src/main.rs:62:33
   |
62 |             File::create(path)?.write_fmt(format_args!("{}", std::process::id()))?;
   |                                 ^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
   |
14 | use std::io::Write;
   |
```

Reviewed By: DurhamG, singhsrb

Differential Revision: D9066112

fbshipit-source-id: f685b75c4032e8388529f6cf8a9724426bd15baa