pathhistory: use block_in_place to fix nested tokio block_on failure
Summary:
This diff is for fixing the following nested `block_on` failure when I am trying to use dagcopytrace in pathcopies():
* 1st `block_on` is in pycopytrace for converting async to sync
* 2nd `block_on` is in `EdenApiTreeStore.trees_blocking` API

```
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks
```

For unittests, we need to use `multi_thread`, otherwise we will get the following runtime error:

```
thread 'tests::rename_tracer_tests::test_trace_commit_added_files' panicked at src/pathops.rs:335:17:
can call blocking only when running on the multi-threaded runtime
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Reviewed By: quark-zju

Differential Revision: D55644276

fbshipit-source-id: cca2ce1c7ecdf04e1a8d403b28b5a4c26bba7444