pyerror: propagate NetworkError
Summary: Tweak pyerror to convert an otherwise-not-handled NetworkError in to Python HttpError (which will trigger the network doctor). This lets Rust code tag errors as NetworkError and have that propagate to Python instead of having pyerror know about all the specific error types that might be network errors.

Reviewed By: quark-zju

Differential Revision: D36639090

fbshipit-source-id: 222cd79415febce85ff0b4fd907d0b4037ca43e8