unbreak mac eden tests allow Bytes and String in c-python code
Summary:
previously the eden tests on my M1 were crashing with this err:

```
HgError: Command [/usr/local/bin/hg --traceback commit -m test foo/new.txt] failed with status -6
stderr:
  Assertion failed: (PyBytes_Check(str_obj)), function _asciitransform, file eden/scm/edenscm/cext/charencode.c, line 181.
```

after debugging this seems to come from the filefoldmap code path:
https://www.internalfb.com/code/fbsource/[6f287df44cebb45baecc1920c86a9aade0a537b6]/fbcode/eden/scm/edenscm/dirstate.py?lines=1599

The issue is that the keys of the dirstate are str objects where the c code in
_asciitransform expects them to be bytes.

notably intel does not seem to trip over this assertion, so the assertion only
seems to happen on arm.

not sure why the assertion only happens there. but anyways ...

We cannot transform the string to bytes in python, because we are not able to
iterate the map in python: https://www.internalfb.com/code/fbsource/[6f287df44ceb]/fbcode/eden/scm/edenscm/eden_dirstate.py?lines=53-70

So we need to make this c function support strings (or at least something in the
c layer support strings).

That's what we are doing here.

We probably could get rid of the support for bytes in this function because ...

There are multiple code paths that call into this function with bytes. There's
this one: https://www.internalfb.com/code/fbsource/[6f287df44cebb45baecc1920c86a9aade0a537b6]/fbcode/eden/scm/edenscm/posix.py?lines=661

but that is doing a conversion from bytes to string right before calling.

and these ones that are dead code paths: https://www.internalfb.com/code/fbsource/[6f287df44cebb45baecc1920c86a9aade0a537b6]/fbcode/eden/scm/edenscm/encoding.py?lines=278%2C300

The first could use string and the second can probably be deleted since we are
on python 3 now: https://www.internalfb.com/code/fbsource/[6f287df44cebb45baecc1920c86a9aade0a537b6]/fbcode/eden/scm/edenscm/encoding.py?lines=489%2C509%2C512%2C516-518

I'll leave it up to the mercurial folks if you want to pursue that option.

Muir and I also looked to see if we could delete the c code altogether, but
that's a bit complicated because python can't iterate an eden dir state, and
this code implicitly uses the c code to iterate the dir state for the python
code. So the python needs to grow the ability to iterate the dirstate, or
larger chunks of this code need to be refactored, I think.

For now I am making the minimal change to get the eden tests running on mac.

Reviewed By: quark-zju, xavierd

Differential Revision: D43962468

fbshipit-source-id: 6145aae4b812f21b7561515544fd7aef956f4e0b