Patch enumset to fix serde feature
Summary:
The `enumset` crate is broken when the target platform and host platform have different features enabled, which is not just a Buck thing, but can happen in Cargo builds too.

`derive(EnumSetType)` was incorrectly looking at whether the "serde" feature is enabled in the **host** platform to decide whether to generate `serialize` and `deserialize` functions in the generated `EnumSetTypePrivate` impl. This is not correct. When using the Cargo v2 feature resolver (edition 2021+), or when using the v1 feature resolver and cross-compiling, it can happen that "serde" is enabled in the host platform and not enabled in the target platform, leading to generated code that does not compile.

The serde-related generated code needs to depend on whether "serde" is enabled in the **target** platform.

Cargo-based repro:

```lang=toml
# Cargo.toml

[package]
name = "repro"
edition = "2024"
publish = false

[dependencies]
enumset = "1"

[build-dependencies]
enumset = { version = "1", features = ["serde"] }
```

```lang=rust
// src/lib.rs

#[derive(enumset::EnumSetType)]
pub enum Enum {}
```

```lang=rust
// build.rs

fn main() {}
```

`cargo check` previously failed like this:

```lang=text,counterexample
error[E0407]: method `serialize` is not a member of trait `enumset::__internal::EnumSetTypePrivate`
 --> src/lib.rs:3:10
  |
3 | #[derive(enumset::EnumSetType)]
  |          ^^^^^^^^^^^^^^^^^^^^ not a member of trait `enumset::__internal::EnumSetTypePrivate`
  |
  = note: this error originates in the derive macro `enumset::EnumSetType` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `serde` in `__internal`
 --> src/lib.rs:3:10
  |
3 | #[derive(enumset::EnumSetType)]
  |          ^^^^^^^^^^^^^^^^^^^^ could not find `serde` in `__internal`
  |
note: found an item that was configured out
 --> $CARGO_HOME/registry/src/index.crates.io-1949cf8c6b5b557f/enumset-1.1.6/src/macros.rs:9:23
  |
9 |     pub use serde2 as serde;
  |                       ^^^^^
note: the item is gated behind the `serde` feature
 --> $CARGO_HOME/registry/src/index.crates.io-1949cf8c6b5b557f/enumset-1.1.6/src/macros.rs:8:11
  |
8 |     #[cfg(feature = "serde")]
  |           ^^^^^^^^^^^^^^^^^
  = note: this error originates in the derive macro `enumset::EnumSetType` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0407]: method `deserialize` is not a member of trait `enumset::__internal::EnumSetTypePrivate`
 --> src/lib.rs:3:10
  |
3 | #[derive(enumset::EnumSetType)]
  |          ^^^^^^^^^^^^^^^^^^^^ not a member of trait `enumset::__internal::EnumSetTypePrivate`
  |
  = note: this error originates in the derive macro `enumset::EnumSetType` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0220]: associated type `Ok` not found for `S`
 --> src/lib.rs:3:10
  |
3 | #[derive(enumset::EnumSetType)]
  |          ^^^^^^^^^^^^^^^^^^^^ associated type `Ok` not found
  |
  = note: this error originates in the derive macro `enumset::EnumSetType` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0220]: associated type `Error` not found for `S`
 --> src/lib.rs:3:10
  |
3 | #[derive(enumset::EnumSetType)]
  |          ^^^^^^^^^^^^^^^^^^^^ associated type `Error` not found
  |
  = note: this error originates in the derive macro `enumset::EnumSetType` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0220]: associated type `Error` not found for `D`
 --> src/lib.rs:3:10
  |
3 | #[derive(enumset::EnumSetType)]
  |          ^^^^^^^^^^^^^^^^^^^^ associated type `Error` not found
  |
  = note: this error originates in the derive macro `enumset::EnumSetType` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0220, E0407, E0433.
For more information about an error, try `rustc --explain E0220`.
error: could not compile `repro` (lib) due to 6 previous errors
```

Reviewed By: diliop

Differential Revision: D77893176

fbshipit-source-id: 2d4811de57c0ecaeabb4d16072740fec87d2dd7d