tp2: fix build error for upcoming tp2 update
Summary:
After updating rust-crates-io the build fails with:

  Command failed with exit code 1.
  stderr: error[E0283]: type annotations required: cannot resolve `std::string::String: std::convert::AsRef<_>`
    --> scm/mononoke/server/repo_listener/src/repo_handlers.rs:80:61
     |
  80 |             let ready_handle = ready.create_handle(reponame.as_ref());
     |                                                             ^^^^^^
  error: aborting due to previous error
  For more information about this error, try `rustc --explain E0283`.

Update code to prevent build error.

Reviewed By: StanislavGlebik

Differential Revision: D14911687

fbshipit-source-id: ecba98acfe36dd1938e144c9bfdd4d27fd6a7311