exclude store_type srcs from store
Summary:
Do not duplicate the `store_type` srcs in the `store` target. This is causing linker issues like:
```
ld64.lld: error: duplicate symbol: facebook::eden::toBackingStoreType(std::__1::basic_string_view<char, std::__1::char_traits<char>>)
>>> defined in BackingStoreType.cpp:13 (fbcode/eden/fs/store/BackingStoreType.cpp:13)
>>>            buck-out/v2/gen/fbcode/730a95ded876953c/eden/fs/store/__store__/libstore.pic.a(BackingStoreType.cpp.pic.o)
>>> defined in BackingStoreType.cpp:13 (fbcode/eden/fs/store/BackingStoreType.cpp:13)
>>>            buck-out/v2/gen/fbcode/730a95ded876953c/eden/fs/store/__store_type__/__objects__/BackingStoreType.cpp.pic.o
```

Reviewed By: MichaelCuevas

Differential Revision: D54766947

fbshipit-source-id: b58927aa50f6a2bbdd3b1c290b49e3f3511f093c