remove unused deps
Summary:
Unused deps with crate name collisions become errors in `1.88.0` e.g.:
```
Action failed: fbcode//billing/delivery_processor/marketplace_partner:lib_delivery_processor_mp (cfg:dev-linux-x86_64-fbcode-platform010-clang19-asan-ubsan-dev#4aa3793168dc7c37) (rustc check)
Remote command returned non-zero exit code 1
Remote action, reproduce with: `frecli cas download-action 242718244351dafdd19177ed0e0f6ef1303593ee4bb233c0231a77df4a179872:145`
Stdout: <empty>
Stderr:
error[E0464]: multiple candidates for `rmeta` dependency `types` found
  --> fbcode/billing/delivery_processor/marketplace_partner/delivery_loader_mp.rs:12:5
   |
12 | use types::Civil;
   |     ^^^^^
   |
   = note: candidate #1: /re_cwd/buck-out/v2/gen/fbcode/4aa3793168dc7c37/aml/pe/scripts/ai_health_checks/__types__/LPPM/libtypes-43fca5cc.rmeta
   = note: candidate #2: /re_cwd/buck-out/v2/gen/fbcode/4aa3793168dc7c37/billing/delivery_processor/common/__types__/LPPM/libtypes-0cc80822.rmeta

error: aborting due to 1 previous error
```

Reviewed By: capickett

Differential Revision: D78038768

fbshipit-source-id: 05455bce27bdd1d5db262687eb4d532c9d855037