python3-sys: upgrade to python 3.10
Summary:
Trying to help with this problem:

  hg --version
  Traceback (most recent call last):
    File "/opt/fb/mercurial/edenscm/__init__.py", line 81, in run
      from . import dispatch
    File "/opt/fb/mercurial/edenscm/dispatch.py", line 27, in <module>
      from . import (
    File "/opt/fb/mercurial/edenscm/cmdutil.py", line 29, in <module>
      from . import (
    File "/opt/fb/mercurial/edenscm/bookmarks.py", line 21, in <module>
      from . import (
    File "/opt/fb/mercurial/edenscm/encoding.py", line 20, in <module>
      from edenscmnative import parsers as charencode
  ImportError: Python minor version mismatch: The Mercurial extension modules were compiled with Python 3.10.9+fb, but Mercurial is currently using Python with sys.hexversion=50857712: Python 3.8.6 (default, Feb 10 2023, 17:15:29)
  [GCC 11.x 20221024 (Facebook) 11.2.1+]

Reviewed By: muirdm

Differential Revision: D49067540

fbshipit-source-id: 3aa673021b706c659bd2676bc448e3ae1edd6f42