Add missing `Eq`.
Running `rustc == 1.76.0`.

The following error was occurring:

```
error: to use a constant of type `FetchMode` in a pattern, `FetchMode` must be annotated with `#[derive(PartialEq, Eq)]`
   --> lib/revisionstore/src/scmstore/tree.rs:261:20
    |
261 |             if let FetchMode::AllowRemote = fetch_mode {
    |                    ^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: the traits must be derived, manual `impl`s are not sufficient
    = note: see https://doc.rust-lang.org/stable/std/marker/trait.StructuralEq.html for details
error: could not compile `revisionstore` (lib) due to 1 previous error; 1 warning emitted
```