changelog: skip commit hash verification for readfiles
Summary:
liubov-dmitrieva reported in P788939965 that commands like:

  hg log -r " reverse(master~1000::master) & not(file(r're:.*'))"

causes lots of 1-by-1 location -> hash lookups. This diff resolves it by
skipping the problematic code path:

  File "edenscm/revset.py", line 1456, in matches
    files = getfiles(x)
  File "edenscm/changelog2.py", line 382, in readfiles
    text = self.revision(node)
  File "edenscm/changelog2.py", line 495, in revision
    p1, p2 = self.parents(node)[:2]
  File "edenscm/changelog2.py", line 648, in parents
    parents = list(self.dag.parentnames(node))
  error.UncategorizedNativeError: Resolving id exceeds threshold 10 set by EDENSCM_REMOTE_ID_THRESHOLD

The troublesome code path was found by setting
`EDENSCM_REMOTE_ID_THRESHOLD=10`.

Reviewed By: zzl0

Differential Revision: D47417522

fbshipit-source-id: 2830e825a362c6a1ea26f2627fef65dd5b7dcf4b