copytrace: disable demandimport during `dbm.open`
Summary:
The `dbm.open` relies `ImportError` to detect unavailable dbm impls:

    if _defaultmod is None:
        for name in _names:
            try:
                mod = __import__(name, fromlist=['open'])
            except ImportError:
                continue
            ...

demandimport can delay the `ImportError` and cause issues later:

    --- test-copytrace-rebase-renamed.t
    +++ test-copytrace-rebase-renamed.t.err
    @@ -20,22 +20,52 @@
       [54bfd3] original commit
       $ hg mv dir1/file1 dir1/file2
       $ hg amend
    -  hint[amend-restack]: descendants of 54bfd3f39556 are left behind - use 'hg restack' to rebase them
    -  hint[hint-ack]: use 'hg hint --ack amend-restack' to silence these hints
    +  Traceback (most recent call last):
    +  ....
    +    File "sapling\ext\copytrace.py", line 257, in _amend
    +      db, error = opendbm(repo, "c")
    +    File "sapling\ext\copytrace.py", line 206, in opendbm
    +      return (opener(path, flag), error)
    +    File "dbm\__init__.py", line 95, in open
    +  AttributeError: module 'dbm.ndbm' has no attribute 'open'
    +  [1]

Fix it by disabling the demandimport in the scope. A long term fix might be
just migrating from dbm to something else (like indexedlog).

Reviewed By: sggutier

Differential Revision: D50389552

fbshipit-source-id: c34cda404d8dd769978f513b413c009d943d02b2