dag: avoid polling SliceSet's inner set twice
Summary:
Pulling the inner set twice could cause panic:

  thread 'nameset::id_static::tests::test_dag_specialized_flatten_id_fast_path_with_slices' panicked at rust/vendor/futures-util-0.3.30/src/stream/unfold.rs:108:21:
  Unfold must not be polled after it returned `Poll::Ready(None)`
  stack backtrace:
     0: std::panicking::begin_panic
               at rustc/library/std/src/panicking.rs:688:12
     1: <futures_util::stream::unfold::Unfold<T,F,Fut> as futures_core::stream::Stream>::poll_next
               at futures-util-0.3.30/src/stream/unfold.rs:108:21
     2: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
               at futures-core-0.3.30/src/stream.rs:120:9
     3: futures_util::stream::stream::StreamExt::poll_next_unpin
               at futures-util-0.3.30/src/stream/stream/mod.rs:1638:9
     4: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
               at futures-util-0.3.30/src/stream/stream/next.rs:32:9
     5: dag::nameset::slice::Iter::next::{{closure}}
               at ./src/nameset/slice.rs:129:73
     6: dag::nameset::slice::Iter::into_stream::{{closure}}::{{closure}}
               at ./src/nameset/slice.rs:188:39
     7: <futures_util::stream::unfold::Unfold<T,F,Fut> as futures_core::stream::Stream>::poll_next
               at futures-util-0.3.30/src/stream/unfold.rs:107:33
     8: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
               at futures-core-0.3.30/src/stream.rs:120:9
     9: <S as futures_core::stream::TryStream>::try_poll_next
               at futures-core-0.3.30/src/stream.rs:196:9
    10: <futures_util::stream::try_stream::try_collect::TryCollect<St,C> as core::future::future::Future>::poll
               at futures-util-0.3.30/src/stream/try_stream/try_collect.rs:46:26
    11: nonblocking::non_blocking
               at lib/nonblocking/src/lib.rs:28:11
    12: nonblocking::non_blocking_result
               at lib/nonblocking/src/lib.rs:40:5
    13: dag::nameset::tests::fmt_iter
               at ./src/nameset.rs:1537:21
    14: dag::nameset::id_static::tests::dbg_flat
               at ./src/nameset/id_static.rs:464:25
    15: dag::nameset::id_static::tests::test_dag_specialized_flatten_id_fast_path_with_slices::{{closure}}
               at ./src/nameset/id_static.rs:588:24
    16: dag::nameset::id_static::tests::with_dag
               at ./src/nameset/id_static.rs:411:9
    17: dag::nameset::id_static::tests::test_dag_specialized_flatten_id_fast_path_with_slices
               at ./src/nameset/id_static.rs:528:9
    18: dag::nameset::id_static::tests::test_dag_specialized_flatten_id_fast_path_with_slices::{{closure}}
               at ./src/nameset/id_static.rs:526:67
    19: core::ops::function::FnOnce::call_once
               at rustc/library/core/src/ops/function.rs:250:5
    20: core::ops::function::FnOnce::call_once
               at rustc/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Add an explicit `ended` state to avoid calling `inner_iter.next()` after it returns `None`.

Reviewed By: zzl0

Differential Revision: D58441120

fbshipit-source-id: c386a2e9727e261f30aa2a67fb03a0eb1233e072