getdeps: set up formatter for PrivHelperConn::MsgType
Summary:
getdeps fails with the following error:

```
/data/users/helsel/scratch/homeZhelselZlocalZfbsource/fbcode_builder_getdeps/installed/fmt-P3XE1sYNqr_xAI-LOfARL5-t0-J79n2DUfI08Mv6Y2Q/include/fmt/base.h:2018:74:   required from ‘constexpr fmt::v11::detail::format_arg_store<Context, NUM_ARGS, 0, DESC> fmt::v11::make_format_args(T& ...) [with Context = fmt::v11::context; T = {const facebook::eden::PrivHelperConn::MsgType, const unsigned int}; long unsigned int NUM_ARGS = 2; long unsigned int NUM_NAMED_ARGS = 0; long long unsigned int DESC = 47; typename std::enable_if<(NUM_NAMED_ARGS == 0), int>::type <anonymous> = 0]’
/data/users/helsel/scratch/homeZhelselZlocalZfbsource/fbcode_builder_getdeps/installed/folly/include/folly/logging/LogStreamProcessor.h:371:52:   required from ‘std::string folly::LogStreamProcessor::formatLogString(folly::StringPiece, const Args& ...) [with Args = {facebook::eden::PrivHelperConn::MsgType, unsigned int}; std::string = std::__cxx11::basic_string<char>; folly::StringPiece = folly::Range<const char*>]’
/data/users/helsel/scratch/homeZhelselZlocalZfbsource/fbcode_builder_getdeps/installed/folly/include/folly/logging/LogStreamProcessor.h:255:28:   required from ‘folly::LogStreamProcessor::LogStreamProcessor(folly::XlogFileScopeInfo*, folly::LogLevel, folly::StringPiece, bool, folly::StringPiece, unsigned int, folly::StringPiece, folly::LogStreamProcessor::FormatType, folly::StringPiece, Args&& ...) [with Args = {facebook::eden::PrivHelperConn::MsgType&, unsigned int&}; folly::StringPiece = folly::Range<const char*>]’
/data/users/helsel/scratch/homeZhelselZlocalZfbsource/fbcode_builder_getdeps/shipit/eden/eden/fs/privhelper/PrivHelperServer.cpp:1207:3:   required from here
/data/users/helsel/scratch/homeZhelselZlocalZfbsource/fbcode_builder_getdeps/installed/fmt-P3XE1sYNqr_xAI-LOfARL5-t0-J79n2DUfI08Mv6Y2Q/include/fmt/base.h:1641:63: error: ‘fmt::v11::detail::type_is_unformattable_for<const facebook::eden::PrivHelperConn::MsgType, char> _’ has incomplete type
 1641 |     type_is_unformattable_for<T, typename Context::char_type> _;
```

This diff adds a formatter for `facebook::eden::PrivHelperConn::MsgType` so it can be used with `fmt`

Reviewed By: MichaelCuevas

Differential Revision: D62392716

fbshipit-source-id: ad897fd41e444a08ad38894d13dfb9763cbdbb54