windows: back out "fix things when CWD is a UNC path"
Summary:
The original diff caused below error, we tried a few fixes (D41331378 (https://github.com/facebook/sapling/commit/d74872799b3adb73e8c3879721d7382bae7abf80), D41377214, D41396613), but didn't work. Revert the original change to unblock Windows build (hopefully).

```
error.HttpError: Server responded 404 Not Found for eager://$TESTTMP\repo_server/commit_revlog_data
```

Original commit changeset: 3aa27b795ab6
Original Phabricator Diff: D41161268 (https://github.com/facebook/sapling/commit/16ff3c9f415cfb966d825cb021ed016cc9d14770)

Reviewed By: quark-zju

Differential Revision: D41402776

fbshipit-source-id: 5b1d83f123406f25cc4c3cd2879d7fd356e21f30