getdeps: use underlying type in foidTypeToString XLOGF error message
Summary:
getdeps fails with the following error:

```
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/folly/include/folly/logging/LogStreamProcessor.h:255:28:   required from ‘folly::LogStreamProcessor::LogStreamProcessor(folly::XlogFileScopeInfo*, folly::LogLevel, folly::StringPiece, bool, folly::StringPiece, unsigned int, folly::StringPiece, folly::LogStreamProcessor::FormatType, folly::StringPiece, Args&& ...) [with Args = {facebook::eden::FilteredObjectIdType&}; folly::StringPiece = folly::Range<const char*>]’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/eden/eden/fs/store/filter/FilteredObjectId.cpp:32:3:   required from here
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-FHukGLl-vQ54P4P_dMfig6Np0_gq5419Adqk0Dqpexo/include/fmt/base.h:1641:63: error: ‘fmt::v11::detail::type_is_unformattable_for<const facebook::eden::FilteredObjectIdType, char> _’ has incomplete type
 1641 |     type_is_unformattable_for<T, typename Context::char_type> _;
```

This diff changes `foidTypeToString` to use the underlying type in the error message to mitigate the issue

Reviewed By: kavehahmadi60

Differential Revision: D62407504

fbshipit-source-id: 9a1f51c9ab535f421591171e5b01b43e34b4bd67