edenfsctl: wrap par file in python.exe on Windows
Summary:
# Context
Commands that fall back to Python started failing on Windows with a cryptic error:

```
Error: failed to execute: "C:\open\scratch\C_ZopenZfbsource\edenfs\redirections\buck-out\v2\gen\fbcode\a95da7dda7e630d2\eden\fs\cli\__edenfsctl__\edenfsctl.par" "start" "--help"

Caused by:
    %1 is not a valid Win32 application. (os error 193)
```

This was caused by trying to run a par file directly instead of wrapping the par in a Python command.

# This diff

This diff fixes the broken behavior by wrapping par files in Python. This doesn't affect production at all; it only affects scenarios where devs run `buck2 run`

Reviewed By: muirdm

Differential Revision: D59665005

fbshipit-source-id: 7b6c85cf9536ff0483b786eb24dbd35d61949d13