pyio: raise UnsupportedOperation instead of IOError for fileno()
Summary:
```
Traceback (most recent call last):
  File "static:sapling.scmposix", line 30, in termsize
    fd = dev.fileno()
OSError: stream does not have a fileno
```

Reviewed By: muirdm

Differential Revision: D50556778

fbshipit-source-id: 7d271b87ae2573aefadeb224b66de11c55d874b0