encoding: use double backslash
In Python 2, '\u' == '\\u'. However, in Python 3, '\u' results in:

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in
position 0-1: truncated \uXXXX escape

The minor change in this patch allows Python 3 to ast parse encoding.py.