git: fix pullhead()
Summary:
```
File "static:sapling.git", line 866, in pullhead
        self._pullraw("HEAD")
    TypeError: Submodule._pullraw() missing 1 required positional argument: 'refspec_lhs'
```

Reviewed By: sggutier

Differential Revision: D56103509

fbshipit-source-id: d0bd7f9591393f8060006dc8535e2f637430eda1