configparser: make non-fb deps optional
Summary:
This should address GitHub build issue:

```
Run cargo test --verbose --target-dir target --manifest-path eden/scm/lib/auth/Cargo.toml
    Updating crates.io index
error: failed to get `hostcaps` as a dependency of package `configparser v0.1.0 (/home/runner/work/eden/eden/eden/scm/lib/configparser)`
    ... which satisfies path dependency `configparser` of package `auth v0.1.0 (/home/runner/work/eden/eden/eden/scm/lib/auth)`

Caused by:
  failed to load source for dependency `hostcaps`

Caused by:
  Unable to update /home/runner/work/eden/eden/common/rust/shed/hostcaps

Caused by:
  failed to read `/home/runner/work/eden/eden/common/rust/shed/hostcaps/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

Reviewed By: yancouto

Differential Revision: D32468108

fbshipit-source-id: ff379436d421849f461508a71b41a7f3f87be7a9