sapling: fix threading cyclic import error when calling traceback
Summary:

Test Plan:

Before:
```
./build/fbcode_builder/getdeps.py --allow-system-packages test --src-dir=. sapling --num-jobs=32 --filter test-fb-ext-grpcheck.t --retry 0
...
-  You should be in devs group.
+  unknown python exception <class 'AttributeError'> Some(AttributeError("partially initialized module 'threading' has no attribute 'RLock' (most likely due to a circular import)")) (no-eol)
+  [1]

```

After:
```
----------------------------------------------------------------------
# Ran 1 tests, 0 skipped, 0 failed.
passed on try 0
```