manylinux: make Python ssl (`_ssl`) use statically linked openssl
Summary:
`manylinux` upstream bumped openssl from 3.0 to 3.5 (https://github.com/pypa/manylinux/issues/1782).
By default, python `_ssl` module dynamically links to the system openssl (libcrypto).

3.5 is too new as a shared library requirement.
Distributions like ubuntu 24 and fedora 42 will fail the version check, and crash like:

    % ./sl version
    Traceback (most recent call last):
      File "static:sapling", line 62, in run
        from . import dispatch
      ...
      File "static:sapling.sslutil", line 19, in <module>
        import ssl
      File "/opt/python/cp312-cp312/lib/python3.12/ssl.py", line 100, in <module>
        import _ssl             # if we can't import it, let the error propagate
        ^^^^^^^^^^^
    ImportError: /lib64/libcrypto.so.3: version `OPENSSL_3.3.0' not found (required by /home/quark/tmp/sl-bin/lib/python3.12/lib-dynload/_ssl.cpython-312-x86_64-linux-gnu.so

The "manylinux" goal is to make the executable "portable" to run on many linux
distros. So this openssl version requirement needs to be relaxed.

We already use static linking for Rust openssl (D76301204).
This diff updates cpython build logic to use static linking too.

Since I'm modifying the Dockerfile, and the GitHub action iterations are slow,
I also patched the python build script to use `-j` to try to improve build
performance.

Reviewed By: giorgidze

Differential Revision: D97017760

fbshipit-source-id: df85e73289663397dca49d016edbc6721270cd18