indexedlog: include wrong meta file content in error message
Summary:
We got errors like:

  error.IndexedLogError: "repo/.hg/store/lfs/pointers/meta": when reading LogMetadata
  in log::OpenOptions::open(Filesystem("repo/.hg/store/lfs/pointers"))
  Caused by 1 errors:
  - failed to fill whole buffer

from Sandcastle. There seems no easy way to get a sample of the broken `meta`
file content. Let's include the file content to make progress on debugging.

Reviewed By: DurhamG

Differential Revision: D30939737

fbshipit-source-id: ccd77f6b67e4aaf75af2248118845fd5b3434ff1