deps: yarn add -W -D @babel/runtime
Summary:
For some reason, `yarn test` in `isl/` starts failing like:

  FAIL  src/__tests__/CommitTreeList.test.tsx
   ● Test suite failed to run

     Cannot find module '.../eden/addons/node_modules/babel-preset-react-app/node_modules/babel/runtime/helpers/interopRequireDefault.js' from 'src/App.tsx'

     Require stack:
       src/App.tsx
       src/__tests__/CommitTreeList.test.tsx

       1 | /**
       2 |  * Copyright (c) Meta Platforms, Inc. and affiliates.
     > 3 |  *
         |             ^
       4 |  * This source code is licensed under the MIT license found in the
       5 |  * LICENSE file in the root directory of this source tree.
       6 |  */

       at Resolver.resolveModule (../node_modules/jest-resolve/build/resolver.js:324:11)
       at Object.<anonymous> (src/App.tsx:3:30)

It seems `addons/node_modules/babel-preset-react-app/node_modules` does not
have `babel` at all. I tried deleting node_modules and re-run yarn but that
does not make a difference. I also tried clean `master` but it fails the same
way.

From https://github.com/facebook/create-react-app/issues/7183, some suggested
adding `babel/runtime` as an explicit dependency. It does populate the missing
`babel` directory and make `yarn test` green again for me.

Reviewed By: evangrayk

Differential Revision: D45369968

fbshipit-source-id: ac4a54188ab6f9e1f62acf478a75c0abe8f383d6