encoding: fix make build by removing local-encoding
Summary:
`local-encoding` was removed in D67531801, let's remove it from autocargo. Otherwise, it will cause the following error when running `make local` on dev server:
```
error: no matching package named `local-encoding` found
location searched: directory source `(redacted)/third-party/rust/vendor` (which is replacing registry `crates-io`)
required by package `sapling-encoding v0.1.0
...
```

Reviewed By: muirdm

Differential Revision: D68019676

fbshipit-source-id: 760be12a3d822bf9b7351491250c50c957b5218b