pycext: add 'stdlib' flag for macOS
Summary:
this diff fixes below error:

```
running: "clang++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "--target=x86_64-apple-darwin" "-mmacosx-version-min=10.7" "-I" "/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11" "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-function" "-fno-common" "-dynamic" "-DNDEBUG" "-g" "-fwrapv" "-O3" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk" "-o" "/private/tmp/sapling-20231113-5024-krmhw6/eden/scm/build/cargo-target/x86_64-apple-darwin/release/build/pycext-4bf2458160d01796/out/713ff949e19e1a67-traceprofimpl.o" "-c" "../../../../sapling/cext/../ext/extlib/traceprofimpl.cpp"
  cargo:warning=clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]

  cargo:warning=../../../../sapling/cext/../ext/extlib/traceprofimpl.cpp:16:10: fatal error: 'algorithm' file not found

  cargo:warning=#include <algorithm>

  cargo:warning=         ^~~~~~~~~~~

  cargo:warning=1 error generated.
```

Reviewed By: quark-zju

Differential Revision: D51282333

fbshipit-source-id: 55adf8870b14d2c0d7897e342f99d6dfed3db4ad