Set default commit timezone
Summary:
Set default commit timezone to  UTC to avoid time missmatches.

While running tests I noticed that the times didn't match:
```
buck test //eden/scm/tests:hg_run_py_tests
File changed: fbcode//eden/scm/tests/diff/hashes.py
waiting for all tests to finish...
✗ Fail: eden/scm/tests:hg_run_py_tests - test_diff_hashes (eden.scm.tests.diff.hashes.TestDiffHashes) (0.0s)
AssertionError: '--- [27 chars]1970 -0800\n+++ b/foo\tThu Jan 01 00:00:00 197[37 chars]ar\n' != '--- [27 chars]1970 +0000\n+++ b/foo\tThu Jan 01 00:00:00 197[37 chars]ar\n'
- --- a/fooThu Jan 01 00:00:00 1970 -0800
?                                   ^ ^
+ --- a/fooThu Jan 01 00:00:00 1970 +0000
?                                   ^ ^
- +++ b/fooThu Jan 01 00:00:00 1970 -0800
?                                   ^ ^
+ +++ b/fooThu Jan 01 00:00:00 1970 +0000
?                                   ^ ^
```
Although ususally we won't be looking to time, make sure that it is set it to as specific a value as possible.

Reviewed By: sggutier

Differential Revision: D37174200

fbshipit-source-id: c9b024f19ade3ce3ffb341f7da263e4dd51a8f31