setup: add missing mpatch library dependency to cstore
Summary:
cstore needs mpatch to function. This fixes errors like:

  # linux
  ImportError: */cstore.so: undefined symbol: mpatch_lfree
  # osx
  abort: dlopen(*/cstore.so, 2): Symbol not found: _mpatch_apply

Test Plan:
```
make clean local
cd tests
rt test-cstore.t
```

Reviewers: #sourcecontrol, durham

Reviewed By: durham

Subscribers: mjpieters

Differential Revision: https://phabricator.intern.facebook.com/D5024117

Signature: t1:5024117:1494293670:007a9f61f0175f4820d7d76de44e0399fe3ab8a9