revlog: fix revlog crash issue
Summary:
we removed the 'None' check of _chunkcache in D47857735, which caused
crash issue when running 'pull' command:

```
File ".../scm/edenscm/revlog.py", line
  808, in _getsegment
    o, d = self._chunkcache
TypeError: cannot unpack non-iterable NoneType object
```

Reviewed By: quark-zju

Differential Revision: D47955093

fbshipit-source-id: 862eb2b0850a6c4eb5b730c4d615524116238e13