indexedlog: turn some panic into errors
Summary:
We have seen slicing panics on NFS, like:

  thread 'main' panicked at 'range end index 14079379 out of range for slice of length 0', eden/scm/lib/indexedlog/src/log/mod.rs:1678:14

Possibly when some files were stale or out of sync (ex. `log` got shorter than
expected somehow) due to NFS weirdness (bad locking?). Let's make them Rust
errors instead of panics for easier error reporting and investigation.

Reviewed By: DurhamG

Differential Revision: D30166177

fbshipit-source-id: 25cbd9c178b24580c176fe9469362fe0020ede95