pyerror: fix dag::Error handling
Summary:
Look for dag::Error directly in addition to inside of hgcommits::Error.

It would be great if we could use the error chain, but thiserror "transparent" causes the containing error to be skipped in the chain, which messes things up.

Reviewed By: DurhamG

Differential Revision: D36491718

fbshipit-source-id: b1cafd05f0b0af36913ecb4fc92cf21a65622187