eden/fs/utils/test/PathMapTest.cpp: avoid warning about set-but-unused argument
Summary:
This avoids the following errors:

  eden/fs/utils/test/PathMapTest.cpp:223:31: error: parameter 'secondArg' set but not used [-Werror,-Wunused-but-set-parameter]

Reviewed By: r-barnes

Differential Revision: D42356496

fbshipit-source-id: 0d236f5e169f71384ebacae69e015c866bdc5f74