Add retries to `sqlblob_gc mark`
Summary:
In prod, I see errors that imply a master move or a one-off DB
failure, like:
```
Error: While executing InsertGeneration query

Caused by:
    Mysql Query failed: Failed The MySQL server is running with the --read-only
    (super) option so it cannot execute this statement.
```
and
```
Error: While executing InsertGeneration query

Caused by:
    Mysql Query failed: TimedOut [7002](MySQL Client) Query timed out (no rows seen, took 10000 ms)
```
Teach garbage marking to retry after a random delay,

Reviewed By: StanislavGlebik

Differential Revision: D25974428

fbshipit-source-id: d905ea2c9da19de79b1b8322193831774c3f1ce9