Fix github URL for graphql-parser
Summary:
Remove an extra forward slash in the URL. Is this a typo?

https://github.com/graphql-rust//graphql-parser --> https://github.com/graphql-rust/graphql-parser

I'm not sure how this was working, I keep running into this error on trunk and cannot do the add/upgrade flow.
```
[henrywang8@devbig3694.ash8 ~/local/fbsource (1694a733a)]$ fbcode/common/rust/tools/reindeer/vendor
You may need to remove the insteadOf block from your .gitconfig
Eden prefetch...
Setting up Eden redirects...
Vendoring /home/henrywang8/local/fbsource/third-party/rust...
[ERROR reindeer] `cd "/home/henrywang8/local/fbsource/third-party/rust" && CARGO_HOME="/home/henrywang8/local/fbsource/third-party/rust/.cargo" RUSTC="/home/henrywang8/local/fbsource/third-party/rust/../../xplat/rust/toolchain/current/basic/bin/rustc" RUSTC_BOOTSTRAP="1" "/home/henrywang8/local/fbsource/third-party/rust/../../xplat/rust/toolchain/current/basic/bin/cargo" "vendor" "--manifest-path" "/home/henrywang8/local/fbsource/third-party/rust/Cargo.toml" "vendor" "--versioned-dirs" "-Zbindeps"` failed:
        Updating git repository `https://github.com/graphql-rust//graphql-parser`
    fatal: remote error:
     graphql-rust//graphql-parser is not a valid repository name
    Visit https://support.github.com/ for help
    error: failed to sync

    Caused by:
      failed to load pkg lockfile

    Caused by:
      failed to load source for dependency `graphql-parser`

    Caused by:
      Unable to update https://github.com/graphql-rust//graphql-parser?rev=8d76425d83c40670570cc325f57c730262f07456#8d76425d

    Caused by:
      failed to fetch into: /home/henrywang8/local/fbsource/third-party/rust/.cargo/git/db/graphql-parser-c1e86e4340dd4183

    Caused by:
      process didn't exit successfully: `git fetch --force --update-head-ok 'https://github.com/graphql-rust//graphql-parser' '+8d76425d83c40670570cc325f57c730262f07456:refs/commit/8d76425d83c40670570cc325f57c730262f07456'` (exit status: 128)

Cleaning up Eden redirects...
Repo cleanup...
```

Reviewed By: zertosh

Differential Revision: D67636897

fbshipit-source-id: dcf83df17a2e94c53ee6fd3b06fe8ddd2eef6176