subtree: add validate_path_exist() for subtree diff
Summary:
This diff adds validate_path_exist() for subtree diff from/to paths. Otherwise, the command
raise below error:

```
  File "scm/sapling/copies.py", line 349, in xdir_copies
    if dag.isancestor(csrcbase, cdstbase):
    # csrcbase = bin('94f00e7526a5eed18ec5a109c8fb18f5dd6dc7d5')
TypeError: Expected type that converts to PyBytes but received NoneType
```

Reviewed By: muirdm

Differential Revision: D67242552

fbshipit-source-id: 0cb0ee1b161f22089aa4878334cc3a5d3c993837