get mononoke green in github CI (#974)
Summary:
X-link: https://github.com/facebookincubator/zstrong/pull/1018

* test-cross-repo-mononoke-git-sot.t deleted, remove from exclusion list
* exclude flaky integration tests

changes done to make this easier:
 * python-click wasn't found in sapling dir, added package mappings for rpm and deb so that we can pick up the installed version
 * add a bit more info to the "unknown python exception" message from hg
 * reduce paths set by getdeps, no point listing non-existing dir, makes it easier to see what is happening


Test Plan:
**Local run of unittest**
```
./build/fbcode_builder/getdeps.py --allow-system-packages build --src-dir=. mononoke
./build/fbcode_builder/getdeps.py --allow-system-packages test--src-dir=. mononoke
```

**Local run of integration test**
```
# first build sapling cli & install system deps
./build/fbcode_builder/getdeps.py --allow-system-packages build --src-dir=. sapling
./build/fbcode_builder/getdeps.py install-system-deps --recursive mononoke_integration
# then test mononoke
./build/fbcode_builder/getdeps.py --allow-system-packages build --no-deps --src-dir=. mononoke_integration
./build/fbcode_builder/getdeps.py --allow-system-packages test --src-dir=. mononoke_integration --num-jobs=4
```

Before, fails
```
AssertionError: The test groups contain not existing tests: ['cross_repo/test-cross-repo-mononoke-git-sot-switch.t'] in /home/runner/work/sapling/sapling/eden/mononoke/tests/integration
```

After, lets see the CI

Reviewed By: quark-zju

Differential Revision: D64827811

Pulled By: ahornby