github: fix non-placeholder gh submit
Summary:
Set head_branch_name on the CommitInfo when preparing params. The `None` was causing an error when submitting more than one pr that looked like:

```
  File ".../edenscm/ext/github/submit.py", line 261, in rewrite_pull_request_body
    base = none_throws(partitions[index + 1][0].head_branch_name)
    # index = 0
  File ".../edenscm/ext/github/none_throws.py", line 14, in none_throws
    assert optional is not None, msg
    # msg = 'Unexpected None'
AssertionError: Unexpected None
```

Note that subimt doesn't currently respect the "workflow" selection and always effects "single" mode. Will address in next diff.

Fixes #519 #511

Reviewed By: quark-zju

Differential Revision: D43198209

fbshipit-source-id: 5c338f8c0e885b72b156d5561380ed4cb501280f