push: fix TypeError when deleting remote bookmark
Summary:
Currently, we append both `tuple` and `list` types to `outbookmarks`, which causes TypeError like below:

```
  - Traceback (most recent call last):
      File "/opt/fb/mercurial/edenscm/commands/__init__.py", line 4984, in push
        pushop = exchange.push(
      File "/opt/fb/mercurial/edenscm/exchange.py", line 506, in push
        _pushdiscovery(pushop)
      File "/opt/fb/mercurial/edenscm/exchange.py", line 620, in _pushdiscovery
        step(pushop)
      File "/opt/fb/mercurial/edenscm/ext/remotenames.py", line 624, in expushdiscoverybookmarks
        return exchange._pushdiscoverybookmarks(pushop)
      File "/opt/fb/mercurial/edenscm/exchange.py", line 757, in _pushdiscoverybookmarks
        pushop.outbookmarks.sort()
    TypeError: '<' not supported between instances of 'tuple' and 'list'
```

Reviewed By: quark-zju

Differential Revision: D42151253

fbshipit-source-id: e9eacc6530d8302ce102f0bed069066ec6932e88