getdeps: avoid using fmt::format with BackingStoreType
Summary:
getdeps fails with the following error:

```
/data/users/helsel/scratch/homeZhelselZlocalZfbsource/fbcode_builder_getdeps/installed/fmt-P3XE1sYNqr_xAI-LOfARL5-t0-J79n2DUfI08Mv6Y2Q/include/fmt/format.h:4365:44:   required from ‘std::string fmt::v11::format(fmt::v11::format_string<T ...>, T&& ...) [with T = {facebook::eden::BackingStoreType&}; std::string = std::__cxx11::basic_string<char>; fmt::v11::format_string<T ...> = fmt::v11::basic_format_string<char, facebook::eden::BackingStoreType&>]’
/data/users/helsel/scratch/homeZhelselZlocalZfbsource/fbcode_builder_getdeps/shipit/eden/eden/common/utils/Throw.h:57:37:   required from ‘void facebook::eden::throwf(fmt::v11::format_string<T ...>, T&& ...) [with E = std::domain_error; T = {facebook::eden::BackingStoreType&}; fmt::v11::format_string<T ...> = fmt::v11::basic_format_string<char, facebook::eden::BackingStoreType&>]’
/data/users/helsel/scratch/homeZhelselZlocalZfbsource/fbcode_builder_getdeps/shipit/eden/eden/fs/store/BackingStoreType.cpp:45:30:   required from here
/data/users/helsel/scratch/homeZhelselZlocalZfbsource/fbcode_builder_getdeps/installed/fmt-P3XE1sYNqr_xAI-LOfARL5-t0-J79n2DUfI08Mv6Y2Q/include/fmt/base.h:1641:63: error: ‘fmt::v11::detail::type_is_unformattable_for<facebook::eden::BackingStoreType, char> _’ has incomplete type
 1641 |     type_is_unformattable_for<T, typename Context::char_type> _;
```

This diff just changes the `throwf` to a `throw_` for the default case to work around this issue.

Reviewed By: jdelliot, MichaelCuevas

Differential Revision: D62392723

fbshipit-source-id: 74c349351e12451ad2d06d27eeb678d1a995104f