github: upgrade from upload-artifact@v3 to v4
Summary:
The v3 seems to be incompatible with the artifact downloading logic. We got errors like:

  Run actions/download-artifact@v4.1.7
  Downloading single artifact
  Error: Unable to download artifact(s): Artifact not found for name: macos-homebrew-arm64-bottle
         Please ensure that your artifact is not expired and the artifact was uploaded using a compatible version of toolkit/upload-artifact.
         For more information, visit the GitHub Artifacts FAQ: https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md

(from https://github.com/facebook/sapling/actions/runs/12129022616/job/33816893587) for all platforms.

Attempt to fix it by upgrading `upload-artifact` so it becomes "compatible".
See also https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Reviewed By: muirdm

Differential Revision: D66680087

fbshipit-source-id: 3a5de659c7b30dc0215eb3db30f6c5dac8742a6a