setup: remove -Werror
Summary:
Newer gcc might add new warnings without notice. Having `-Werror` might break
build with newer gcc. For example, I got the following error with gcc 7.2:

```
In file included from /usr/include/python2.7/Python.h:80:0,
                 from hgext/extlib/cstore/py-cstore.cpp:14:
./hgext/extlib/cstore/py-treemanifest.h: In function ‘PyObject* treemanifest_hasdir(py_treemanifest*, PyObject*)’:
/usr/include/python2.7/object.h:769:22: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
/usr/include/python2.7/boolobject.h:27:31: note: in expansion of macro ‘Py_INCREF’
 #define Py_RETURN_TRUE return Py_INCREF(Py_True), Py_True
                               ^~~~~~~~~
./hgext/extlib/cstore/py-treemanifest.h:536:5: note: in expansion of macro ‘Py_RETURN_TRUE’
     Py_RETURN_TRUE;
     ^~~~~~~~~~~~~~
/usr/include/python2.7/object.h:769:22: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
/usr/include/python2.7/boolobject.h:28:32: note: in expansion of macro ‘Py_INCREF’
 #define Py_RETURN_FALSE return Py_INCREF(Py_False), Py_False
                                ^~~~~~~~~
./hgext/extlib/cstore/py-treemanifest.h:538:5: note: in expansion of macro ‘Py_RETURN_FALSE’
     Py_RETURN_FALSE;
     ^~~~~~~~~~~~~~~
./hgext/extlib/cstore/py-treemanifest.h: In function ‘PyObject* treemanifest_text(py_treemanifest*, PyObject*, PyObject*)’:
/usr/include/python2.7/object.h:769:22: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
./hgext/extlib/cstore/py-treemanifest.h:1309:5: note: in expansion of macro ‘Py_INCREF’
     Py_INCREF(Py_False);
     ^~~~~~~~~
hgext/extlib/cstore/py-cstore.cpp: In function ‘void initcstore()’:
/usr/include/python2.7/object.h:769:22: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
hgext/extlib/cstore/py-cstore.cpp:37:3: note: in expansion of macro ‘Py_INCREF’
   Py_INCREF(&cdatapack_type);
   ^~~~~~~~~
/usr/include/python2.7/object.h:769:22: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
hgext/extlib/cstore/py-cstore.cpp:45:3: note: in expansion of macro ‘Py_INCREF’
   Py_INCREF(&treemanifestType);
   ^~~~~~~~~
/usr/include/python2.7/object.h:769:22: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
hgext/extlib/cstore/py-cstore.cpp:53:3: note: in expansion of macro ‘Py_INCREF’
   Py_INCREF(&datapackstoreType);
   ^~~~~~~~~
/usr/include/python2.7/object.h:769:22: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
hgext/extlib/cstore/py-cstore.cpp:61:3: note: in expansion of macro ‘Py_INCREF’
   Py_INCREF(&uniondatapackstoreType);
   ^~~~~~~~~
```

Explicitly suppressing warnings might break older gcc that does not support
those flags. Ideally the fix would be changing the source code. But in this
case it's in a library that cannot be easily fixed here in this repo.

Therefore just remove `-Werror`.


Test Plan: Confirm `make build` works after the change.

Reviewers: durham, #mercurial

Reviewed By: durham

Subscribers: durham

Differential Revision: https://phabricator.intern.facebook.com/D6695948

Signature: 6695948:1515633376:67f40f0489b69a70700e181313d8ad837a76a2c9