ghstack: fix ghstack land crash
Summary:
Currently, `sl ghstack land` pass a dict type to `github_gh_cli.format_param`, which doesn't support dict. This diff is to fix that by destructuring the dict into basic types [1] (Thanks Michael).

```
  File "../eden/scm/ghstack/github_gh_cli.py", line 134, in format_param
    raise RuntimeError(f"unexpected param: {key}={value}")
RuntimeError: unexpected param: input={'refId': 'REF_kwDOIYMvu7lyZWZzL2hlYWRzL2doL3p6bDAvMC9iYXNl', 'oid': 'aa4e8a0224f3e6aaf6b5677df6a5f20a9e19f4fb'}
```
[1] https://atheros.ai/blog/graphql-quick-tip-how-to-pass-variables-in-graphiql

Reviewed By: bolinfest

Differential Revision: D41096086

fbshipit-source-id: 91026602e3514308f2dbd2ea252b191e4d1af1d8