Work around clippy crash in multiplexedblob_wal
Summary:
Before this change,
```
arc rust-clippy //eden/mononoke/blobstore:multiplexedblob_wal-unittest
```
failed ungraciously with:
```
File changed: fbcode//eden/mononoke/blobstore/multiplexedblob_wal/src/multiplex.rs
File changed: fbcode//eden/fs/store/git/GitBackingStore.cpp
Action failed: fbcode//eden/mononoke/blobstore:multiplexedblob_wal-unittest (rustc bin-pic-shared-metadata/multiplexedblob_wal_unittest-metadata bin,pic,metadata [clippy])
Remote command returned non-zero exit code 101
Reproduce locally: `frecli cas download-action e2c5c9e58703ce3c526ab116fd1cce8c0302c307:94`
stdout:
stderr:
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/tools/clippy/clippy_lints/src/ptr.rs:234:49

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.67

query stack during panic:

#0 [analysis] running analysis passes on this crate

end of query stack

Buck UI: https://www.internalfb.com/buck2/8802c9ab-ae8f-4b18-83a4-2b4992bc8f5b
RE: reSessionID-26b8008f-93cc-402a-bdde-fff3596ed795  Up: 1.0 KiB  Down: 0 B
Jobs completed: 5. Time elapsed: 50.7s. Cache hits: 0%. Commands: 1 (cached: 0, remote: 1, local: 0)
BXL SUCCEEDED
```

I found out the issue was happening in the `cloned` macro with the `key` by progressively isolating the code that was causing issues.

This code is equivalent, but happens not to hit this clippy bug.

Reviewed By: yancouto

Differential Revision: D44027145

fbshipit-source-id: 678e8d870754162665aa7d50c5839e116b5af186