setup: make ctypes import lazy
Summary:
Some environment does not have a working `ctypes` module.

For example, when building cpython from source, if the `ffi` library and its
development headers are not installed, the `_cyptes` native module will fail to
build, and `setup.py` will fail to run:

    Traceback (most recent call last):
      File "/somewhere/home/foo/software/sapling/eden/scm/setup.py", line 26, in <module>
        import ctypes.util
      File "/somewhere/home/foo/software/cpython/Lib/ctypes/__init__.py", line 8, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'

Fix it by avoiding `import ctypes.util` at the start of `setup.py`.

Reviewed By: lmvasquezg

Differential Revision: D59618334

fbshipit-source-id: 92e5252744abbfe9ab908c3a4d72760d4a48ae56