Show stderr directly for status/log
Summary:
If `sl status` / `sl log` hit an error in sl, it would raise an ExecaError which is sent to the UI by extracting the `.message`. This looks like:
```
Command failed with exit code 255: sl log --template {node) {desc|firstline) {author) {committerdate|isodatese) {phase) {bookmarks % {book..
Error: Command failed with exit code 255: sl log --template {node)
{desc|firstline}
{author}
{committerdate| isodatesec} {phase)
{bookmarks & '{bookmark}\0'} {remotenames % '{remotename} \0'}
{parents % "{node}\0"} {ifcontains(rev, revset('.'), '@')}
(file_adds |json}
(file_mods |json}
(file_dels |json}
{mutations % "{operation}: (successors % "{node)"},"} {predecessors % "(node), "}
roninteractive-Configextenstons.blackbostingbooknarks) + heads (drart())) & date(-24)) + •) "
abort: failed to read from file '/data/users/evangrayk/fbsource/.hg/requires': Transport endpoint is not connected (os error 107)
at tt (/home/evangrayk/.vscode-fb-insiders/extensions/facebook.sapling-scm-|
0.1.54000/dist/extension.js: 1:19002)
at /home/evangrayk/.vscode-fb-insiders/extensions/facebook.sapling-scm-
0.1.54000/dist/extension.js:1:29087
at process-processTicksAndRejections (node: internal/process/task_queues: 95:5) at async Ru (/home/evangrayk/.vscode-fb-insiders/extensions/facebook.sapling-scm-
0.1.54000/dist/extension.js:1:173176)
at async /home/evangrayk/.vscode-fb-insiders/extensions/facebook.sapling-scm-
0.1.54000/dist/extension.js:
```

This is a lot of noise. The only part we care about is:
```
abort: failed to read from file '/data/users/evangrayk/fbsource/.hg/requires': Transport endpoint is not connected (os error 107)
```

This diff makes this easier to read by trimming the command from the start of the error message. Then the byline of the error notice already shows the problem immediately in most cases. This is way easier to read as a user.

Reviewed By: quark-zju

Differential Revision: D61221302

fbshipit-source-id: f33e2f6a42c8b9d8fa999295cfa2aa08514f26eb