disable transfer speed timeout for upload changesets
Summary:
disable transfer speed timeout for upload changesets

Currently, server sends the "upload_changesets" response once it is fully completed,
disable min speed transfer check to avoid premature termination of requests.

https://www.internalfb.com/code/fbsource/[b8c0216665249f8d691eaa155572372313bf2b7d]/fbcode/eden/mononoke/edenapi_service/src/handlers/commit.rs?lines=342

The timeout is more relevant to transferring data endpoints. This endpoint is not fast.

This is to fix the

```
error.HttpError: [28] Timeout was reached (Operation too slow. Less than 1500 bytes/sec transferred the last 60 seconds)
```
in S397015

We still have another timeout mentioned here: D50969586
Currently, 15 minutes, so we should manage to upload larger stacks.

Reviewed By: quark-zju

Differential Revision: D54085068

fbshipit-source-id: b9bfbcf104ceb21b70b32dc47cf65ff5d9fb3635