Don't include commit title in PR body (#822)
Summary:
Don't include commit title in PR body

Seems redundant to include the commit title in both the PR body and title, so this strips out the title.

Had some trouble building to test this out (ran into `error[E0658]: use of unstable library feature 'stdsimd'`)

Pull Request resolved: https://github.com/facebook/sapling/pull/822

Reviewed By: zzl0

Differential Revision: D52938280

Pulled By: quark-zju

fbshipit-source-id: ffe70aa9c35125f09de5d2e0e63243af96e61236