python-modules: improve codegen compatibility with libpython.a build
Summary:
Docker manylinux build issue:

  [root@afaf6d685b03 codegen-exe]# cargo run -- --sys-path /src/sapling/eden/scm --out /tmp/a.rs
  ...
  Traceback (most recent call last):
    File "<string>", line 34, in <module>
  ImportError: /opt/python/cp312-cp312/lib/python3.12/lib-dynload/binascii.cpython-312-x86_64-linux-gnu.so: undefined symbol: PyExc_ValueError
  ...

This is because the `build.rs` executable lacks of the `-Wl,--export-dynamic` linker flag (see also D75251375).

The binascii module isn't actually used. So let's drop it.
I cleaned up outdated docs to match the current state.

Reviewed By: giorgidze

Differential Revision: D96959585

fbshipit-source-id: 6f0cb337eab9a3292685536997b4c60a56428c56