perftweaks: ignore errors caused by trackupdatesize
When enabling the extensions and run tests in core hg, it sometimes raises

  RepoLookupError: unknown revision '-1'

from the trackupdate code path. This is not a critical feature so let's just
ignore the error.

Differential Revision: https://phab.mercurial-scm.org/D1500