sqliterevmap: break ".hashes()" cycle in a safer way
The `fromsvn()` revset implementation could cause weakref error when using
sqliterevmap like:

  File "hgsubversion/util.py", line 357, in <lambda>
    return subset.filter(lambda r: tonode(r) in hashes)
  File "hgsubversion/maps.py", line 542, in __contains__
    return self.get(key) != None
  File "hgsubversion/maps.py", line 533, in get
    for row in self.revmap._query(
  ReferenceError: weakly-referenced object no longer exists

Basically the seemingly harmless assignment could break surprisingly:

  # dangerous: `hashes` does not have a reference on `meta.revmap` and may
  # become unavailable after `meta`, `revmap` are released.
  hashes = meta.revmap.hashes()

Avoiding cycles is still nice. This patch removes `revmap._hashes` so the
revmap no longer owns a reference of a `ReverseRevMap` object so the
`ReverseRevMap` object no longer needs to use weakref for `self.revmap`.

This could actually be caught by `comprehensive/test_sqlite_revmap.py`.
I was not careful enough verifying the "fromsvn()" patch.