getdeps: call foidTypeToString in throwf in FilteredBackingStore
Summary:
getdeps fails with the following error:

```
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-FHukGLl-vQ54P4P_dMfig6Np0_gq5419Adqk0Dqpexo/include/fmt/format.h:4365:44:   required from ‘std::string fmt::v11::format(fmt::v11::format_string<T ...>, T&& ...) [with T = {facebook::eden::FilteredObjectIdType&}; std::string = std::__cxx11::basic_string<char>; fmt::v11::format_string<T ...> = fmt::v11::basic_format_string<char, facebook::eden::FilteredObjectIdType&>]’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/eden/eden/common/utils/Throw.h:57:37:   required from ‘void facebook::eden::throwf(fmt::v11::format_string<T ...>, T&& ...) [with E = std::runtime_error; T = {facebook::eden::FilteredObjectIdType&}; fmt::v11::format_string<T ...> = fmt::v11::basic_format_string<char, facebook::eden::FilteredObjectIdType&>]’
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/shipit/eden/eden/fs/store/FilteredBackingStore.cpp:160:31:   required from here
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fmt-FHukGLl-vQ54P4P_dMfig6Np0_gq5419Adqk0Dqpexo/include/fmt/base.h:1641:63: error: ‘fmt::v11::detail::type_is_unformattable_for<facebook::eden::FilteredObjectIdType, char> _’ has incomplete type
 1641 |     type_is_unformattable_for<T, typename Context::char_type> _;
      |                                                               ^
```

This diff calls `foidTypeToString` to mitigate the issue

Differential Revision: D62397034

fbshipit-source-id: 1fb6aa53b556657b02c77f519fe0799012b50667