commitcloud: attempt to fix no '_localstr_to_mysql' error
Summary:
There are certain commits that failed to backup with this error:

  remote: Traceback (most recent call last):
  remote:   File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 590, in _callcatch
  remote:     return scmutil.callcatch(ui, func)
  remote:   File "/usr/lib64/python2.7/site-packages/mercurial/scmutil.py", line 160, in callcatch
  remote:     return func()
  remote:   File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 571, in _runcatchfunc
  remote:     return _dispatch(req)
  remote:   File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 1357, in _dispatch
  remote:     lui, repo, cmd, fullargs, ui, options, d, cmdpats, cmdoptions
  remote:   File "/usr/lib64/python2.7/site-packages/hgext/clienttelemetry.py", line 91, in _runcommand
  remote:     return orig(lui, repo, cmd, fullargs, ui, options, d, cmdpats, cmdoptions)
  remote:   File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 1061, in runcommand
  remote:     ret = _runcommand(ui, options, cmd, d)
  remote:   File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 1369, in _runcommand
  remote:     return cmdfunc()
  remote:   File "/usr/lib64/python2.7/site-packages/mercurial/dispatch.py", line 1354, in <lambda>
  remote:     d = lambda: util.checksignature(func)(ui, *args, **strcmdopt)
  remote:   File "/usr/lib64/python2.7/site-packages/mercurial/util.py", line 1319, in check
  remote:     return func(*args, **kwargs)
  remote:   File "/usr/lib64/python2.7/site-packages/mercurial/util.py", line 1319, in check
  remote:     return func(*args, **kwargs)
  remote:   File "/usr/lib64/python2.7/site-packages/hgext/directaccess.py", line 118, in wrapwitherror
  remote:     return orig(ui, repo, *args, **kwargs)
  remote:   File "/usr/lib64/python2.7/site-packages/mercurial/util.py", line 1319, in check
  remote:     return func(*args, **kwargs)
  remote:   File "/usr/lib64/python2.7/site-packages/mercurial/commands/__init__.py", line 5911, in serve
  remote:     s.serve_forever()
  remote:   File "/usr/lib64/python2.7/site-packages/mercurial/sshserver.py", line 107, in serve_forever
  remote:     while self.serve_one():
  remote:   File "/usr/lib64/python2.7/site-packages/mercurial/sshserver.py", line 138, in serve_one
  remote:     rsp = wireproto.dispatch(self.repo, self, cmd)
  remote:   File "/usr/lib64/python2.7/site-packages/hgext/pushrebase/__init__.py", line 266, in _wireprodispatch
  remote:     return orig(repo, proto, command)
  remote:   File "/usr/lib64/python2.7/site-packages/mercurial/wireproto.py", line 671, in dispatch
  remote:     res = func(repo, proto, *args)
  remote:   File "/usr/lib64/python2.7/site-packages/mercurial/wireproto.py", line 1166, in unbundle
  remote:     r = exchange.unbundle(repo, gen, their_heads, "serve", proto._client())
  remote:   File "/usr/lib64/python2.7/site-packages/hgext/pushrebase/__init__.py", line 305, in unbundle
  remote:     result = orig(repo, cg, heads, source, url)
  remote:   File "/usr/lib64/python2.7/site-packages/hgext/hgsql.py", line 332, in unbundle
  remote:     return orig(repo, cg, *args, **kwargs)
  remote:   File "/usr/lib64/python2.7/site-packages/mercurial/exchange.py", line 2138, in unbundle
  remote:     op = bundle2.processbundle(repo, cg, op=op)
  remote:   File "/usr/lib64/python2.7/site-packages/mercurial/bundle2.py", line 469, in processbundle
  remote:     processparts(repo, op, unbundler)
  remote:   File "/usr/lib64/python2.7/site-packages/hgext/infinitepush/__init__.py", line 1394, in processparts
  remote:     storebundle(op, cgparams, bundlefile)
  remote:   File "/usr/lib64/python2.7/site-packages/hgext/infinitepush/__init__.py", line 1484, in storebundle
  remote:     index.addbundle(key, nodesctx)
  remote:   File "/usr/lib64/python2.7/site-packages/hgext/infinitepush/sqlindexapi.py", line 170, in addbundle
  remote:     data,
  remote:   File "/usr/lib/python2.7/site-packages/mysql/connector/cursor.py", line 567, in executemany
  remote:     self.execute(operation, params)
  remote:   File "/usr/lib/python2.7/site-packages/mysql/connector/cursor.py", line 477, in execute
  remote:     stmt = operation % self._process_params(params)
  remote:   File "/usr/lib/python2.7/site-packages/mysql/connector/cursor.py", line 355, in _process_params
  remote:     "Failed processing format-parameters; %s" % err)
  remote: ProgrammingError: Failed processing format-parameters; 'CustomConverter' object has no attribute '_localstr_to_mysql'

I'm not sure which code path creates localstr exactly. But it seems to be
created for non-utf8 strings. Since Python 2's `str` is actually `bytes` that
can store non-utf8 losslessly, let's just define the missing method that casts
localstr to str (bytes).

The change is not backported to hgsql intentionally since hgsql hasn't seen
similar issues.

Reviewed By: liubov-dmitrieva

Differential Revision: D13069914

fbshipit-source-id: 8185dc457f8e6ac98a484f5bc6d6e7008ddcee02