parsers: fix Py2.4 argument parsing issue
Since d0ec15e840e5, we were getting this strange message with Py2.4:

 TypeError: argument 1 must be impossible<bad format char>, not int

..because we were using the 'n' type specifier introduced in 2.5.

It turns out that offset is actually a revision number index, which
ought to be an int anyway. So we store it in an int, use the 'i'
specifier, rely on Py_ParseTuple for range checking, and rename it to
avoid type confusion.