fastlog: avoid background threads that might SIGABRT
Summary:
Make fastlog uses a regular generator and just one generatorset, instead of a
background thread + queue + nested generatorsets. The "combinator" that takes
threads becomes unnecessary after D45898263 and is removed.

This avoids the SIGABRT issue which could be reproduced relatively easily like:

   export CHGDISABLE=1
   # likely SIGABRT in the first 10 runs
   for i in `seq 100`; do hg log -r 'max(follow(fbcode/buck2,master))' --pager=off || { echo FAIL!; return 1 }; done

Example SIGABRT backtraces in gdb:

    (gdb) r log -r 'max(follow(fbcode/buck2,master))' --pager=off --verbose --debug --config fastlog.debug=remote
    Starting program: hg log -r 'max(follow(fbcode/buck2,master))' --pager=off --verbose --debug --config fastlog.debug=remote
    [Thread debugging using libthread_db enabled]
    ...
    thread '<unnamed>' panicked at 'panic in a function that cannot unwind', library/core/src/panicking.rs:123:5
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    thread caused non-unwinding panic. aborting.

    Thread 14 "hg" received signal SIGABRT, Aborted.
    [Switching to Thread 0x7fffc7a00700 (LWP 785327)]
    0x00007ffff6a4eacf in raise () from /lib64/libc.so.6
    (gdb) bt
    0  0x00007ffff6a4eacf in raise () from /lib64/libc.so.6
    1  0x00007ffff6a21ea5 in abort () from /lib64/libc.so.6
    2  0x0000555557fb9677 in std::sys::unix::abort_internal () at library/std/src/sys/unix/mod.rs:350
    3  0x0000555557fb1eaa in std::panicking::rust_panic_with_hook () at library/std/src/panicking.rs:711
    4  0x0000555557fb1b42 in std::panicking::begin_panic_handler::{{closure}} () at library/std/src/panicking.rs:581
    5  0x0000555557fb0226 in std::sys_common::backtrace::__rust_end_short_backtrace () at library/std/src/sys_common/backtrace.rs:150
    6  0x0000555557fb1892 in rust_begin_unwind () at library/std/src/panicking.rs:579
    7  0x0000555557fdb223 in core::panicking::panic_nounwind_fmt () at library/core/src/panicking.rs:93
    8  0x0000555557fdb2d1 in core::panicking::panic_nounwind () at library/core/src/panicking.rs:123
    9  0x0000555557fdb3f3 in core::panicking::panic_cannot_unwind () at library/core/src/panicking.rs:171
    10 0x00005555563ae8c4 in cpython::conversion::ToPyObject::with_borrowed_ptr (self=0x7fffc79ff158, f=..., py=...) at ../../../third-party/rust/vendor/cpython-0.7.1/src/conversion.rs:55
    11 cpython::objectprotocol::ObjectProtocol::call (py=..., args=..., kwargs=..., self=<optimized out>) at ../../../third-party/rust/vendor/cpython-0.7.1/src/objectprotocol.rs:214
    12 pythreading::RGeneratorIter::next_internal (self=<optimized out>, py=..., iternext=<optimized out>) at src/lib.rs:405
    13 0x00005555563b2264 in pythreading::RGeneratorIter::__next__ (py=...) at src/lib.rs:389
    14 0x00005555563b3714 in pythreading::RGeneratorIter::create_instance::TYPE_OBJECT::wrap_unary::{{closure}} (py=...)
        at ../../../third-party/rust/vendor/cpython-0.7.1/src/py_class/slots.rs:321
    15 cpython::function::handle_callback::{{closure}} () at ../../../third-party/rust/vendor/cpython-0.7.1/src/function.rs:220
    16 std::panicking::try::do_call (data=<optimized out>) at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487
    17 std::panicking::try (f=...) at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451
    18 0x00005555563b2609 in std::panic::catch_unwind (f=...) at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140
    19 cpython::function::handle_callback (_location=..., f=..., _c=...) at ../../../third-party/rust/vendor/cpython-0.7.1/src/function.rs:218
    20 pythreading::RGeneratorIter::create_instance::TYPE_OBJECT::wrap_unary (slf=0x7fffefa613d0) at ../../../third-party/rust/vendor/cpython-0.7.1/src/py_class/slots.rs:318
    21 0x00007ffff65e1518 in _PyEval_EvalFrameDefault () from /lib64/libpython3.8.so.1.0
    22 0x00007ffff659f02f in _PyFunction_Vectorcall () from /lib64/libpython3.8.so.1.0
    23 0x00007ffff65e11dd in _PyEval_EvalFrameDefault () from /lib64/libpython3.8.so.1.0
    24 0x00007ffff659f02f in _PyFunction_Vectorcall () from /lib64/libpython3.8.so.1.0
    25 0x00007ffff65e11dd in _PyEval_EvalFrameDefault () from /lib64/libpython3.8.so.1.0
    26 0x00007ffff659f02f in _PyFunction_Vectorcall () from /lib64/libpython3.8.so.1.0
    27 0x00007ffff659fb24 in method_vectorcall () from /lib64/libpython3.8.so.1.0
    28 0x00007ffff659798f in PyObject_Call () from /lib64/libpython3.8.so.1.0
    29 0x00007ffff662ec5e in t_bootstrap () from /lib64/libpython3.8.so.1.0
    30 0x00007ffff65ee5a4 in pythread_wrapper () from /lib64/libpython3.8.so.1.0
    31 0x00007ffff5c081ca in start_thread () from /lib64/libpthread.so.0
    32 0x00007ffff6a39e73 in clone () from /lib64/libc.so.6

    (gdb) info threads
      Id   Target Id                                            Frame
      1    Thread 0x7ffff7fe6d80 (LWP 784691) "hg"              0x00007ffff650f274 in visit_decref () from /lib64/libpython3.8.so.1.0
      2    Thread 0x7ffff4a00700 (LWP 785063) "ctrl-c"          0x00007ffff6b1f9b4 in read () from /lib64/libc.so.6
      3    Thread 0x7ffff4600700 (LWP 785066) "tokio-runtime-w" 0x00007ffff6b2ee87 in epoll_wait () from /lib64/libc.so.6
      ....
      10   Thread 0x7fffee600700 (LWP 785073) "tokio-runtime-w" 0x00007ffff6a399bd in syscall () from /lib64/libc.so.6
      11   Thread 0x7fffee200700 (LWP 785074) "rust-progress"   0x00007ffff6af9868 in nanosleep () from /lib64/libc.so.6
      13   Thread 0x7fffd4a00700 (LWP 785135) "hg"              0x00007ffff6b2667f in select () from /lib64/libc.so.6
    * 14   Thread 0x7fffc7a00700 (LWP 785327) "hg" (Exiting)    0x00007ffff6a4eacf in raise () from /lib64/libc.so.6

    (gdb) thread 1
    [Switching to thread 1 (Thread 0x7ffff7fe6d80 (LWP 784691))]
    0  0x00007ffff650f274 in visit_decref () from /lib64/libpython3.8.so.1.0
    (gdb) bt
    0  0x00007ffff650f274 in visit_decref () from /lib64/libpython3.8.so.1.0
    1  0x00007ffff650bc0f in func_traverse () from /lib64/libpython3.8.so.1.0
    2  0x00007ffff6528e94 in collect.constprop () from /lib64/libpython3.8.so.1.0
    3  0x00007ffff664f192 in _PyGC_CollectNoFail () from /lib64/libpython3.8.so.1.0
    4  0x00007ffff664f43a in PyImport_Cleanup () from /lib64/libpython3.8.so.1.0
    5  0x00007ffff66519ff in Py_FinalizeEx () from /lib64/libpython3.8.so.1.0
    6  0x000055555627f9d5 in hgcommands::python::py_finalize () at src/python.rs:136
    7  <hgcommands::hgpython::HgPython as core::ops::drop::Drop>::drop::{{closure}} () at src/hgpython.rs:237
    8  tracing::span::Span::in_scope (self=0x7fffffffafc0, f=...) at ../../../third-party/rust/vendor/tracing-0.1.37/src/span.rs:1102
    9  0x000055555615651a in <hgcommands::hgpython::HgPython as core::ops::drop::Drop>::drop (self=<optimized out>) at src/hgpython.rs:237
    10 0x0000555556130936 in core::ptr::drop_in_place<hgcommands::hgpython::HgPython> () at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ptr/mod.rs:490
    11 hgcommands::run::dispatch_command (io=0x7fffffffcde0, dispatcher=..., cwd=..., in_scope=..., start_time=...) at src/run.rs:240
    12 hgcommands::run::run_command::{{closure}} () at src/run.rs:148
    13 0x000055555612dbbd in hgcommands::run::run_command (args=..., io=0x7fffffffcde0) at src/run.rs:133
    14 0x00005555561242da in hgmain::main () at src/main.rs:114

Note it involves threads, GC, rust-cpython, and `Py_Finalize`.
See also https://github.com/dgrunwald/rust-cpython/pull/244.

Reviewed By: muirdm

Differential Revision: D45898265

fbshipit-source-id: ce94763c7249f83237472f1fc4b4abad1011230c