filters: fix oss build
Summary:
This diff fixes the following oss build error

```
$ make oss
...
error: feature `fb` includes `sapling-edenfs-client/fb`, but `sapling-edenfs-client` is not a dependency
  --> lib/commands/debugcommands/cmddebugfilterid/Cargo.toml:21:6
   |
21 | fb = ["sapling-edenfs-client/fb"]
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
error: failed to get `cmddebugfilterid` as a dependency of package `commands v0.1.0 (/Users/zhaolong/fbsource/fbcode/eden/scm/lib/commands)`
    ... which satisfies path dependency `commands` of package `hgmain v0.1.0 (/Users/zhaolong/fbsource/fbcode/eden/scm/exec/hgmain)`

Caused by:
  failed to load source for dependency `cmddebugfilterid`
...
```

Reviewed By: MichaelCuevas

Differential Revision: D85565880

fbshipit-source-id: 7992b5c3b5053e8a01a12c9d27c960c710889178