pyerror: don't strip off anyhow context
Summary: Instead of stripping anyhow context off all errors, only strip within the concrete error handler "specific_error_handler". This way, the fallback error handler (that produces the beloved RustError) gets the top level error with all the anyhow context.

Reviewed By: DurhamG

Differential Revision: D35602091

fbshipit-source-id: 547ae7e1a2352af74817f90ab08cadb0fce65efc