vfs: normalize fstype and case sensitivity errors
Summary:
See previous diff for context. This is especially tricky to debug (since
building and testing on Windows is slow).

Previously, one might get this error on Windows:

    File "static:sapling.vfs", line 429, in _rustvfs
      vfs = bindings.io.vfs(self.base, destructive=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ProcessLookupError: [Errno 3] $ENOTDIR$.

This turns out to be the steps during vfs initialization, before NoFollowRoot,
are using OS-provided errors.

Normalize to improve compatibility.

Reviewed By: muirdm

Differential Revision: D105422238

fbshipit-source-id: 4d3747f6485c9d80c8e61242b64fe0e8b1707e03