amend: fix unamend with no predecessors
Summary:
When mutation is enabled, and no precessors exists, the predecessors can be
None, leading to hg crashing due to:
  TypeError: object of type 'NoneType' has no len()

Reported by sas: P118684245

Reviewed By: quark-zju

Differential Revision: D17960775

fbshipit-source-id: 05488dbc52edbc32c323612ea86fe9e94076a126