computeInitialParams: do not require `window` to be defined
Summary:
It is undefined in some test environments:

  FAIL extension/blame/__tests__/blame.test.ts
    ● Test suite failed to run

      The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
      Consider using the "jsdom" test environment.

      ReferenceError: window is not defined

        18 | function computeInitialParams(): Map<InitialParamKeys, string> {
        19 |   let initialParams: Map<InitialParamKeys, string> | undefined;
      > 20 |   if (window.location.search) {
           |   ^
        21 |     initialParams = new Map([...new URLSearchParams(window.location.search).entries()]);
        22 |     logger.log('Loaded initial params from URL: ', initialParams);
        23 |     if (islPlatformName() === 'browser') {

Reviewed By: muirdm, evangrayk

Differential Revision: D62469870

fbshipit-source-id: 1394dc8e3368e246540e607b1e8edd39ce28ab21