cli_rs: Use from_nanos instead of new
Summary:
Duration::new() takes in a `u32` for the nanoseconds parameter but `from_nanos` takes in a u64. This hopefully fixes some out-of-range errors that xavierd was seeing:

```
Error: out of range integral type conversion attempted

Caused by:
    out of range integral type conversion attempted
```

Reviewed By: xavierd

Differential Revision: D32813694

fbshipit-source-id: 9c05ac32d6c0d2ab8dfda94b101185122e0be064