Fix one new failure import
Summary:
This is from a nontextual conflict between D18617488 and D18577341 which landed at the same time.

```
error[E0432]: unresolved import `failure`
  --> scm/mononoke/mononoke_api/src/changeset_path.rs:15:5
   |
15 | use failure::err_msg;
   |     ^^^^^^^ help: a similar path exists: `failure_ext::failure`
```

Reviewed By: Imxset21

Differential Revision: D18665138

fbshipit-source-id: 31bdf696afe0cae8f9862793fcc079febf5094f9