fsmonitor: fix compatibility with IPython
Summary:
See the added comment. The stacktrace looks like:

  File "hg\hgext\debugshell.py", line 69, in debugshell
    IPython.embed(header=bannermsg)
  File "IPython\terminal\embed.py", line 383, in embed
    frame.f_code.co_filename, frame.f_lineno), **kwargs)
  File "traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "IPython\terminal\embed.py", line 158, in __init__
    super(InteractiveShellEmbed,self).__init__(**kw)
  File "IPython\terminal\interactiveshell.py", line 441, in __init__
    self.init_prompt_toolkit_cli()
  File "IPython\terminal\interactiveshell.py", line 273, in init_prompt_toolkit_cli
    self._eventloop = create_eventloop(self.inputhook)
  File "prompt_toolkit\shortcuts.py", line 95, in create_eventloop
    return Loop(inputhook=inputhook, recognize_paste=recognize_win32_paste)
  File "prompt_toolkit\eventloop\win32.py", line 39, in __init__
    self._event = _create_event()
  File "prompt_toolkit\eventloop\win32.py", line 189, in _create_event
    return windll.kernel32.CreateEventA(pointer(SECURITY_ATTRIBUTES()), BOOL(True), BOOL(False), None)
  ctypes.ArgumentError: argument 1: <type 'exceptions.TypeError'>: expected LP_c_ulong instance instead of LP_SECURITY_ATTRIBUTES

Reviewed By: DurhamG

Differential Revision: D13422915

fbshipit-source-id: c36fb5ac1fcae6fcf5dc13e13b62e4288587476c