wdir: bump wdirrev to i64::MAX
Summary:
The `wdirrev` is currently `i32::MAX`, which sometimes (although rare) does
not play well with the `u64` Rust dag range. People run into crashes when
using `wdir()` with blame or log sometimes. `wdir()` was marked (by upstream)
as "experimental" and told them to `debugrebuildchange` to mitigate. Recently,
`wdir()` is used more in official ISL features like partial selection, and ISL
users sometimes run into similar issues. So let's try to fix it by bumping it
to `i64::MAX`.

The crashes look like:

  File "static:sapling.revset", line 2439, in wdir
    if node.wdirrev in subset or isinstance(subset, fullreposet):
  File "static:sapling.smartset", line 835, in __contains__
    node = self._tonode(rev)
  error.UncategorizedNativeError: bug: Cannot convert 2147483647 to x~n form using heads 2434154575. This is unexpected. It indicates some serious bugs in graph calculation or the graph is corrupted (ex. has cycles).)"

Note: This is a bandaid fix. A cleaner fix would be proper "virtual" commit
support in the dag, for example, `Group::VIRTUAL = 2` for virtual commits
that never write to disk, then dynamically assign them on repo/working copy
initialization/change so those commits can work with "regular" dag queries. But
that's a large change.

Reviewed By: zzl0

Differential Revision: D51762900

fbshipit-source-id: 734cdeec4bd5fc468abac7e9a97d4fc529512e72