test-fb-hgext-treemanifest-prefetch: disable the test for fsmonitor
Summary:
It's exceeding unix domain socket length limit:

  AssertionError: 2018-06-22T13:48:50,820: [] /tmp/hgtests.8M8JR4/child3/test-fb-hgext-treemanifest-prefetch.t-remotefilelog.true.shallowrepo.true.watchman/sock: path is too long

Talked with wez. Watchman does not want to workaround the issue by using
chdir like chg[1]. The main reason is changing cwd could break
thread-safety, especially when used as a library. chg is single-threaded and
does not have the concern.

[1]: https://www.mercurial-scm.org/repo/hg/rev/c80c16a8a0b092f7b0dd89169ecfc7bc6c1e1a5e

Reviewed By: DurhamG, singhsrb

Differential Revision: D8596333

fbshipit-source-id: 347a42fcd40d4ab075ca9c24f7c9ce4c8fa519b0