fix oss build
Summary:
config variable doesn't exist in oss build since D53334733

```
error[E0425]: cannot find value `config` in this scope
  --> fbcode/eden/scm/lib/commands/debugcommands/cmddebugdumpinternalconfig/src/lib.rs:80:19
   |
80 |     let _ = (ctx, config);
   |                   ^^^^^^ not found in this scope

```

Reviewed By: muirdm

Differential Revision: D53480514

fbshipit-source-id: 30b13a6825d16ce8f075d7d66222b669a40ac117