lib: remove unused C code
Summary:
This is a hg-sever backport of fix from D27659634 (https://github.com/facebookexperimental/eden/commit/8e8aaa61d6742f0b447f8afce3bd8bf16551bcf7)

Those are not used. Recently we saw build issues like:

  lib/third-party/sha1dc/sha1.c:8:10: fatal error: string.h: No such file or directory
   #include <string.h>
            ^~~~~~~~~~

Possibly by some compiler flags disabling stdlib. Since we don't need
the C code let's just remove them.

Reviewed By: StanislavGlebik

Differential Revision: D28096283

fbshipit-source-id: 6c5390d26264e1e39f99b29dec8608d92e5ae572