dag: relax assertion on group of `Id`
Summary:
In certain code paths, an `Id` with invalid group might be passed in to the
query interface. The answer should be simply "not found", instead of a panic.

Related backtrace and test:

  thread 'main' panicked at fbcode/eden/scm/lib/dag/dag-types/src/id.rs:194:9:                                                                                                                                   :(
  invalid group: 255
  stack backtrace:
     0: rust_begin_unwind
               at rust/toolchain/sysroot/1.78.0/library/std/src/panicking.rs:645:5
     1: core::panicking::panic_fmt
               at rust/toolchain/sysroot/1.78.0/library/core/src/panicking.rs:72:14
     2: <dag_types::id::Id>::is_virtual
               at eden/scm/lib/dag/dag-types/src/id.rs:194:9
     3: <dag::idmap::indexedlog_idmap::IdMap as dag::ops::IdConvert>::vertex_name::{closure#0}
               at eden/scm/lib/dag/src/idmap/indexedlog_idmap.rs:193:12
     4: <dag::namedag::AbstractNameDag<dag::iddag::IdDag<dag::iddagstore::indexedlog_store::IndexedLogStore>, dag::idmap::indexedlog_idmap::IdMap, dag::namedag::indexedlog_namedag::IndexedLogNameDagPath, dag::namedag::indexedlog_namedag::NameDagState> as dag::ops::IdConvert>::vertex_name::{closure#0}
               at rust/toolchain/sysroot/1.78.0/library/core/src/future/future.rs:123:9
     5: <tracing::instrument::Instrumented<revsets::utils::resolve_revnum::{closure#0}> as core::future::future::Future>::poll
               at rust/toolchain/sysroot/1.78.0/library/core/src/future/future.rs:123:9
     6: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<revsets::utils::resolve_revnum::{closure#0}>>
               at ./third-party/rust/vendor/tokio-1.37.0/src/runtime/park.rs:281:63
     7: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::scheduler::multi_thread::MultiThread>::block_on<tracing::instrument::Instrumented<revsets::utils::resolve_revnum::{closure#0}>>::{closure#0}, core::result::Result<dag_types::id::VertexName, dag::errors::DagError>>
               at ./third-party/rust/vendor/tokio-1.37.0/src/runtime/context/blocking.rs:66:9
     8: async_runtime::block_on::<revsets::utils::resolve_revnum::{closure#0}>
               at ./third-party/rust/vendor/tokio-1.37.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
     9: revsets::utils::resolve_single
               at eden/scm/lib/revsets/src/utils.rs:255:24
    10: <repo::repo::Repo>::resolve_commit
               at eden/scm/lib/repo/src/repo.rs:553:9
    11: cmdgoto::run
               at eden/scm/lib/commands/commands/cmdgoto/src/lib.rs:181:24
    ...
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

  --- test-git-export.t
  +++ test-git-export.t.err
  @@ -605,19 +605,56 @@
   Additions should be properly marked even in the middle of a merge

     $ hg up -r -2
  -  0 files updated, 0 files merged, 1 files removed, 0 files unresolved
  +  # Python Exception in Shell interpreter:
  +  # Stack
  +  #   File "/usr/locaplatform010/lib/python3.10/runpy.py", line 196, in _run_module_as_main
  +  #     return _run_code(code, main_globals, None,
  +  #   File "/usr/locaplatform010/lib/python3.10/runpy.py", line 86, in _run_code
  +  #     exec(code, run_globals)
  +  #   File "eden/scm/sapling/testing/single.py", line 88, in <module>
  +  #     exitcode = main()
  +  #   File "eden/scm/sapling/testing/single.py", line 72, in main
  +  #     runtest(testid, exts, mismatchcb)
  +  #   File "eden/scm/sapling/testing/t/runner.py", line 267, in runtest
  +  #     return runttest(testid, exts, mismatchcb)
  +  #   File "eden/scm/sapling/testing/t/runner.py", line 426, in runttest
  +  #     exec(compiled, pyenv)
  +  #   File "eden/scm/tests/__pycache__/ttest/test-git-export.py", line 284, in <module>
  +  #     _run_once()
  +  #   File "eden/scm/tests/__pycache__/ttest/test-git-export.py", line 269, in _run_once
  +  #     checkoutput(sheval('hg up -r -2\n'), '0 files updated, 0 files merged, 1 files removed, 0 files unresolved\n', src='$ hg up -r -2\n', srcloc=606, outloc=607, endloc=608, indent=2, filename='eden/scm/tests/test-git-export.t')
  +  #   File "eden/scm/sapling/testing/t/runtime.py", line 275, in sheval
  +  #     out = sh.sheval(code, env, onerror=OnError.WARN_ABORT)
  +  #   File "eden/scm/sapling/testing/sh/interp.py", line 38, in sheval
  +  #     res = interpcode(code, env, onerror=onerror)
  +  #   File "eden/scm/sapling/testing/sh/interp.py", line 54, in interpcode
  +  #     return interpvec(trees, env, onerror=onerror)
  +  # Traceback (most recent call last):
  +  #   File "eden/scm/sapling/testing/sh/interp.py", line 76, in interpvec
  +  #     nextres = interp(tree, env)
  +  #   File "eden/scm/sapling/testing/sh/interp.py", line 66, in interp
  +  #     result = interpfunc(v, env)
  +  #   File "eden/scm/sapling/testing/sh/interp.py", line 125, in interplist
  +  #     res = interp(v["first"], env)
  +  #   File "eden/scm/sapling/testing/sh/interp.py", line 66, in interp
  +  #     result = interpfunc(v, env)
  +  #   File "eden/scm/sapling/testing/sh/interp.py", line 66, in interp
  +  #     result = interpfunc(v, env)
  +  #   File "eden/scm/sapling/testing/sh/interp.py", line 248, in interpsimplecommand
  +  #     ret = cmdfunc(env)
  +  #   File "eden/scm/sapling/testing/sh/stdlib.py", line 74, in wrapper
  +  #     ret = commandfunc(**kwargs)
  +  #   File "eden/scm/sapling/testing/ext/hg.py", line 269, in hg
  +  #     exitcode = bindings.commands.run(env.args, stdin, stdout, stderr)
  +  # SystemError: Rust panic: invalid group: 255
  +  [127]

Reviewed By: muirdm, zzl0

Differential Revision: D58375239

fbshipit-source-id: 1ad7237ed610b6fe918d91a8090b20ea6c890e31