memory: Remove failing unit test
Summary:
This test was added a few days ago in D56701219 and has been failing ever since.

In [the sandcastle logs](https://www.internalfb.com/sandcastle/workflow/1265511495293864711/actions) for oss-mononoke-linux-getdeps, we can see:
```
failures:

---- test::test_get_stats_no_max_set stdout ----
thread 'test::test_get_stats_no_max_set' panicked at common/memory/src/lib.rs:63:9:
assertion failed: stats.is_err()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    test::test_get_stats_no_max_set

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

```

Reviewed By: gustavoavena

Differential Revision: D56830459

fbshipit-source-id: 62145b8d3972d8c1b3263fb31e3559390d1f58ba