pyerror: rename RustError to UncategorizedNativeError
Summary:
The name RustError is kind of confusing:
- Some people confuse it and get bad impression on the Rust language.
- The name is not like Exception, or RuntimeError that are considered bad
  practice, but it is "one type catching all" type that is a bad practice.

Rename it to `UncategorizedNativeError` so it's clear:
- It's an uncategorized error that is unlikely a good practice.
- It does not intend to hurt reputation of the Rust language.
- It is from the native code, Rust, C, or C++.

Reviewed By: muirdm

Differential Revision: D43335812

fbshipit-source-id: 30ae3fa18d6f06963a7556399bee7dcb647ab1d5