python-modules: improve error reporting in codegen
Summary:
I was investigating a build failure in the OSS linux docker image. The current
logic prints unreadable `pytraceback`, although it does include the error
message:

  error: failed to run custom build command for `python-modules v0.1.0 (/src/sapling/eden/scm/lib/python-modules)`

  Caused by:
    process didn't exit successfully: `/src/sapling/eden/scm/build/cargo-target/debug/build/python-modules-70f94fe2359384a0/build-script-build` (exit status: 101)
    --- stderr

    thread 'main' (951) panicked at lib/python-modules/build.rs:16:64:
    called `Result::unwrap()` on an `Err` value: PyErr { ptype: <class 'ImportError'>, pvalue: Some(ImportError('/opt/python/cp312-cp312/lib/python3.12/lib-dynload/binascii.cpython-312-x86_64-linux-gnu.so: undefined symbol: PyExc_ValueError')), ptraceback: Some(<traceback object at 0x7f3110170cc0>) }
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

This diff makes it print the Python backtrace so I can look at which line in
`pycompile.py` triggered the error:

  [root@afaf6d685b03 codegen-exe]# cargo run -- --sys-path /src/sapling/eden/scm --out /tmp/a.rs
  ...
  Traceback (most recent call last):
    File "<string>", line 34, in <module>
  ImportError: /opt/python/cp312-cp312/lib/python3.12/lib-dynload/binascii.cpython-312-x86_64-linux-gnu.so: undefined symbol: PyExc_ValueError
  ...

Differential Revision: D96956130

fbshipit-source-id: 1cd76e92d304b0acb8be24013237ff069dfe34e2