reviewstack: fix verify addons/ folder github ci
The container image was missing the gh command line, resulting in CI errors.   Then found it was intemittently failing due to logging after finish, also fixed.

Test plan:

Run the ci.  Before, broken with:
```
Error: Unhandled error. (Error: GhNotInstalledError: Error: Command failed with ENOENT: gh api graphql -f searchQuery=repo:facebook/sapling is:pr author:@me -F numToFetch=100 --hostname github.com -f query=
    query YourPullRequestsQuery($searchQuery: String!, $numToFetch: Int!) {
  search(query: $searchQuery, type: ISSUE, first: $numToFetch) {
    nodes {
      ... on PullRequest {
```

Then found it was intemittently failing due to logging after finish with:
```
  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions".

      at console.error (../node_modules/@jest/console/build/BufferedConsole.js:163:10)
      at spawnError (node_modules/fb-watchman/index.js:173:13)
      at ChildProcess.<anonymous> (node_modules/fb-watchman/index.js:198:5)
```

Given watch was disabled, added the --no-watchman option as well.

After, works